Refresh.GameServer/Middlewares/NotFoundLogMiddleware.cs
This fixes an exception on startup with fresh runs
=> NotFoundLogMiddleware: Dont try to read unimplemented endpoints file if missing

.github/workflows/dotnet.yml, .github/workflows/release.yml, Refresh.GameServer/Middlewares/DigestMiddleware.cs, Refresh.GameServer/Middlewares/WebsiteMiddleware.cs, Refresh.GameServer/Refresh.GameServer.csproj, Refresh.GameServer/Startup.cs
CI now automatically downloads the latest artifact from [refresh-web](https://github.com/LittleBigRefresh/refresh-web), and packages it with the artifact it creates when building Refresh.
This also rewrites the Release workflow, ensuring building is only done once to keep changes to building behaviour consistent. For example, I can foresee dotnet.yml being updated without release.yml being updated causing problems when a tag is pushed. This almost happened while making this PR.
=> Website: Ability to host from Refresh, bundle with CI builds

Refresh.GameServer/Endpoints/Api/LevelApiEndpoints.cs, Refresh.GameServer/Endpoints/Game/ActivityEndpoints.cs, Refresh.GameServer/Endpoints/Game/Levels/LevelEndpoints.cs, Refresh.GameServer/Types/Levels/Categories/ByUserLevelCategory.cs, Refresh.GameServer/Types/Levels/Categories/GameCategory.cs, Refresh.GameServer/Types/Levels/Categories/LevelCategory.cs, Refresh.GameServer/Types/Levels/Categories/SearchLevelCategory.cs, Refresh.GameServer/Types/Lists/GameCategoryList.cs, Refresh.GameServer/Types/Lists/GameMinimalLevelResultsList.cs
Closes #32
This required a small refactor of the categories system, passing skip & count into the system instead of it being acquired from the request's context.
Search is not implemented.
=> Implement LBP3 Categories

Refresh.GameServer/Authentication/Token.cs, Refresh.GameServer/Authentication/TokenGame.cs, Refresh.GameServer/Authentication/TokenGameUtility.cs, Refresh.GameServer/Authentication/TokenPlatform.cs, Refresh.GameServer/Database/RealmDatabaseContext.Tokens.cs, Refresh.GameServer/Database/RealmDatabaseProvider.cs, Refresh.GameServer/Endpoints/Api/AuthenticationApiEndpoints.cs, Refresh.GameServer/Endpoints/Game/Handshake/AuthenticationEndpoints.cs, Refresh.GameServer/Refresh.GameServer.csproj, Refresh.GameServer/Types/Activity/Groups/UserActivityGroup.cs, Refresh.GameServer/Types/Lists/GameFavouriteUserList.cs, Refresh.GameServer/Types/Report/GriefReport.cs, Refresh.GameServer/Types/Report/InfoBubble.cs, Refresh.GameServer/Types/Report/Marqee.cs, Refresh.GameServer/Types/Report/Player.cs, Refresh.GameServer/Types/Report/ScreenElements.cs, Refresh.GameServer/Types/Report/ScreenRect.cs, Refresh.GameServer/Types/Report/Slot.cs, Refresh.sln.DotSettings
First part of #19 - this allows Refresh to know what platform and game the user is playing on.
=> Track game and platform when authenticating

Refresh.GameServer/Database/GameDatabaseContext.Photos.cs, Refresh.GameServer/Endpoints/Game/CommentEndpoints.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Request/GameLevelRequest.cs, Refresh.GameServer/Endpoints/Game/Levels/LeaderboardEndpoints.cs, Refresh.GameServer/Endpoints/Game/Levels/PublishEndpoints.cs, Refresh.GameServer/Endpoints/Game/RelationEndpoints.cs, Refresh.GameServer/Endpoints/Game/ReportingEndpoints.cs, Refresh.GameServer/Endpoints/Game/ResourceEndpoints.cs, Refresh.GameServer/Endpoints/Game/UserEndpoints.cs, Refresh.GameServer/RefreshGameServer.cs, Refresh.GameServer/Services/MatchService.cs, Refresh.GameServer/Services/TimeProviderService.cs, Refresh.GameServer/Time/IDateTimeProvider.cs, Refresh.GameServer/Time/SystemDateTimeProvider.cs, Refresh.GameServer/Types/Comments/GameComment.cs, Refresh.GameServer/Types/Matching/GameRoom.cs, Refresh.GameServer/Types/Matching/MatchMethods/FindRoomMethod.cs, Refresh.GameServer/Types/Matching/MatchMethods/UpdatePlayersInRoomMethod.cs, Refresh.GameServer/Types/Matching/MatchMethods/UpdateRoomDataMethod.cs, Refresh.GameServer/Types/Report/GameReport.cs, Refresh.GameServer/Types/Report/ScreenElements.cs, RefreshTests.GameServer/GameServer/TestRefreshGameServer.cs, RefreshTests.GameServer/Tests/Matching/MatchingTests.cs, RefreshTests.GameServer/Time/MockDateTimeProvider.cs
This does some code cleanup and sanitizes user inputs a lot more (+ a fix for grief reports)
=> Verify all the things + fix grief reports

Refresh.GameServer/Endpoints/Game/RelationEndpoints.cs
If we return Unauthorized, the client spams the server until it gets a 200 OK, which it never will, leading to an infinite loading loop.
=> Return 200 OK on PSP when a user tries to do an invalid favourite action

Refresh.GameServer/Types/UserData/Leaderboard/SerializedMultiLeaderboardResponse.cs
It should not have been `scores.TotalItems`, that causes intermittent crashes
=> Send player count 1 for PSP leaderboards

Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameUserResponse.cs
Closes #173
I believe we should be filtering the count for each game, eg. LBP2 levels shouldnt count towards the LBP1 count, and LBP1 shouldnt count towards the LBP PSP count, but this is fine for now, and at least fills in this count so *something* is displayed in-game
=> Implement UsedSlots for LBP1/3/PSP

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseContext.Relations.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs, Refresh.GameServer/Endpoints/Game/Levels/LeaderboardEndpoints.cs, Refresh.GameServer/Types/Legacy/LegacyGameLevel.cs, Refresh.GameServer/Types/Relations/PlayLevelRelation.cs
This is only used on PSP, so the logic is only enabled on PSP callers
Closes #178
=> Implement count query parameter for play/user/{id}

Refresh.GameServer/Database/GameDatabaseContext.Photos.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Request/ApiUpdateUserRequest.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiExtendedGameUserResponse.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs, Refresh.GameServer/Endpoints/Game/ReportingEndpoints.cs, Refresh.GameServer/Services/CommandService.cs, Refresh.GameServer/Types/Photos/SerializedPhotoSubject.cs, Refresh.GameServer/Types/Report/GameReport.cs, Refresh.GameServer/Types/UserData/GameUser.cs
This adds photo support to PSP, and allows you to take really quick photos (with UI) on the mainline games almost anywhere too
Marking as draft as [this](https://github.com/Beyley/Refresh/blob/59c21971bec14b7f59b85bf4c7a1ece933fe1054/Refresh.GameServer/Endpoints/Game/ReportingEndpoints.cs#L37) needs to be resolved, so we can remove [this hack](https://github.com/Beyley/Refresh/blob/98b7e77e1e0341b914746fd22515388370999855/Refresh.GameServer/Types/Photos/SerializedPhotoSubject.cs#L26), but im not sure what the range of values are supposed to be
=> Add option to redirect grief reports to photos

Refresh.GameServer/Endpoints/Game/ReviewEndpoints.cs, RefreshTests.GameServer/Tests/Users/ActivityEndpointsTests.cs
This doesnt verify the data *returned* by /lbp/stream is valid but this at least tests that the endpoint doesnt error when it shouldn't.
=> 100% test coverage with ActivityEndpoints

Refresh.GameServer/Endpoints/ApiV3/LevelApiEndpoints.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameUserResponse.cs, Refresh.GameServer/Endpoints/Game/Levels/LevelEndpoints.cs, Refresh.GameServer/Endpoints/Game/ModerationEndpoints.cs, Refresh.GameServer/RefreshContext.cs, Refresh.GameServer/RefreshGameServer.cs, Refresh.GameServer/Services/CommandService.cs, Refresh.GameServer/Services/LevelListOverrideService.cs, RefreshTests.GameServer/GameServer/TestRefreshGameServer.cs, RefreshTests.GameServer/TestContext.cs, RefreshTests.GameServer/Tests/Commands/CommandParseTests.cs, RefreshTests.GameServer/Tests/Levels/LevelListOverrideTests.cs
Will let you easily go to a level from the website (I imagine a button that says 'play now!' ~~that will trigger this) or let you jump into a level by its SHA1/GUID as #200 suggests~~ will come in a separate PR
=> Ability for server to override level pages

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiGameLevelResponse.cs, Refresh.GameServer/RefreshContext.cs, Refresh.GameServer/RefreshGameServer.cs, Refresh.GameServer/Types/Levels/Categories/CategoryService.cs, Refresh.GameServer/Types/Levels/Categories/CoolLevelsCategory.cs, Refresh.GameServer/Types/Levels/GameLevel.cs, Refresh.GameServer/Workers/CoolLevelsWorker.cs, Refresh.sln.DotSettings
Closes #250
This PR implements the algorithm described in #250, with the exception of decay factor which now applies to negative score. The multiplier is multiplied by 2 to make decay half as effective towards negative score.
This also introduces the relevant category in `CategoryService`, adds a `float Score` field to `GameLevel`s, and makes the field accessible to the API.
This system is written to be tweakable and expandable later down the line, although I have fiddled with the defaults already to make them reasonable. I haven't properly messed with logarithmic scaling as I wasn't able to get good results, but I think this can be addressed later down the line.
=> Implement Cool Levels

Refresh.GameServer/CommandLineManager.cs, Refresh.GameServer/Database/GameDatabaseContext.Assets.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiGameAssetResponse.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs, Refresh.GameServer/Endpoints/Game/Levels/LevelEndpoints.cs, Refresh.GameServer/Extensions/GameAssetExtensions.cs, Refresh.GameServer/Importing/AssetImporter.cs, Refresh.GameServer/Importing/Importer.cs, Refresh.GameServer/RefreshGameServer.cs, Refresh.GameServer/Types/Assets/GameAsset.cs
Closes #24 and closes #66
This PR implements support for parsing the dependency tree in binary game assets, and records the size of all assets.
=> Track more asset metadata

RefreshTests.GameServer/Tests/Levels/LevelListOverrideTests.cs
This restores 100% tost coverage for LevelEndpoints
=> LevelListOverrideTests: Basic CanGetOverriddenLevels test

Refresh.GameServer/Authentication/GameAuthenticationProvider.cs, RefreshTests.GameServer/Tests/Authentication/TokenAbuseTests.cs, RefreshTests.GameServer/Tests/Levels/LevelListOverrideTests.cs
https://discord.com/channels/1049223665243389953/1049225857350254632/1173004094185668639
=> Prevent token use across different API types

Refresh.GameServer/Database/GameDatabaseContext.Reports.cs, Refresh.GameServer/Database/GameDatabaseContext.Users.cs, Refresh.GameServer/Endpoints/Game/ModerationEndpoints.cs, Refresh.GameServer/Endpoints/Game/ReportingEndpoints.cs, Refresh.GameServer/Services/CommandService.cs, RefreshTests.GameServer/TestContext.cs, RefreshTests.GameServer/Tests/Reporting/ReportingEndpointsTests.cs
Not 100% due to unreachable switch cases, disabling those would require adding ugly #pragma lines, so i didnt bother
=> Add test coverage for grief reports

Refresh.GameServer/Endpoints/Game/ReportingEndpoints.cs, RefreshTests.GameServer/Tests/Reporting/ReportingEndpointsTests.cs
More PSP weirdness + allow grief reports on missing levels, just incase some weirdness happens, like a level is deleted after creation, and someone happened to start playing it, and you want to grief report a player in your game or something, unlikely, but we probably should allow it anyway
=> ReportingEndpoints: Dont error on invalid level + dont return error on PSP

Refresh.GameServer/Endpoints/Game/Levels/FilterSettings/LevelFilterSettings.cs
Right now we return a 500 InternalServerError, which crashes the game and the console.
Whoops!
=> LevelFilterSettings: LBP3 sometimes sends `dontCare`

Refresh.GameServer/Endpoints/Game/ModerationEndpoints.cs
Currently we try to parse every filter request as a command, which causes spam in the console, as all the commands fail to be parsed.
=> ModerationEndpoints: Dont try to parse every message as a command

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Endpoints/Game/Levels/PublishEndpoints.cs
=> Minor refactor to handling of level republishes

Refresh.GameServer/Database/GameDatabaseContext.Relations.cs
LBP PSP sends the rate level request before the play level request, making this check fail.
=> GameDatabaseContext: Dont check whether user has played level during rate on PSP

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Endpoints/Game/Levels/FilterSettings/LevelFilterSettings.cs, RefreshTests.GameServer/Tests/Levels/LevelTests.cs
Closes #122
Previously, we were using a globally shared instance of `Random` when calculating the random order of levels. This caused levels to appear multiple times in the list and caused others to get potentially missed entirely.
By using a consistent seed we can negate both of those problems and ensure the full list gets hit consistently.
To fix, introduce the client's `seed` parameter as an available parameter to use in the filter settings. We can then use this to create a new `Random` object on each call of `GetRandomLevel()` with the new seed.
This will require a change in `refresh-web` to make the website generate a random seed, since if we do not find a seed value server-side we simply use `0`.
=> Make RandomLevelsCategory use seed from game

Refresh.GameServer/Endpoints/Game/Levels/LeaderboardEndpoints.cs, RefreshTests.GameServer/Tests/Levels/ScoreLeaderboardTests.cs
Closes #142
Currently, Refresh does not validate the ScoreType (aka the game mode or player count) when submitting scores. This isn't too big of a deal since the game only checks certain score types, but it's quite trivial to protect against so we might as well.
To do this, we simply validate whether the score type is either between 1-4 players in co-op mode or 7 for versus mode.
We *could* do some further validation, checking the level's version and type but I think this is enough to stop most abuse.
=> Simple validation for ScoreType when submitting scores

Refresh.GameServer/Database/GameDatabaseContext.Leaderboard.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiGameScoreResponse.cs, Refresh.GameServer/Endpoints/Game/Levels/LeaderboardEndpoints.cs, Refresh.GameServer/Types/UserData/Leaderboard/GameSubmittedScore.cs, RefreshTests.GameServer/TestContext.cs, RefreshTests.GameServer/Tests/Levels/ScoreLeaderboardTests.cs
Closes #241 
The main reason we'd want to do this is not only is it a cool metric to track, but also the fact that we support both PS3 and RPCS3, and naturally RPCS3 can be more susceptible to gameplay glitches depending on your settings. I just think it's better to distinguish the two in some way.
Eventually down the line, we'll also be able to track PPSSPP or Vita3K when those two games achieve networking support in LBP for the same reasons.
We simply add a new property onto `GameSubmittedScore` that contains the platform. Then, we use a best-effort migration that tries to match each game to the most relevant platform. For the mainline games, this will be PS3, LBP Vita is Vita, and LBP PSP is PSP.
We obviously can't go back in time and tell if a particular score was done on RPCS3 so we …
=> Track the platform scores were achieved on

Refresh.Common/Refresh.Common.csproj, Refresh.Common/RefreshServer.cs, Refresh.GameServer/Refresh.GameServer.csproj, Refresh.GameServer/RefreshGameServer.cs, Refresh.sln, RefreshTests.GameServer/GameServer/TestRefreshGameServer.cs
I am currently starting the beginnings of the Room Server discussed in #282. While creating the new project I noticed I was rewriting a lot of code regarding management and bootstrapping, so I decided to do a bit of refactoring.
I created a new project named `Refresh.Common` which contains a new `RefreshServer` class. The normal `RefreshGameServer` extends from this.
`RefreshServer` bootstraps Bunkum and logging functionality, and `RefreshGameServer` now solely manages the workers and injecting of services into Bunkum.
Had to do some weird stuff regarding initialization due to some Bunkum weirdness that came back to bite me in the ass, but it all works out in the end.
=> Refactor RefreshGameServer to support multiple server types

Refresh.GameServer/Database/GameDatabaseContext.Leaderboard.cs, Refresh.GameServer/Types/UserData/Leaderboard/SerializedMultiLeaderboardResponse.cs
Closes #135
LBP uses the raw values for a leaderboard entry's rank written in a response. It doesn't increment by itself - each score is expected to have a correct rank value. Turns out we were calculating these via iteration. While not a problem itself, the problem stems from the fact that we were starting the calculation from 0 and not 1.
This caused leaderboard results to start from `#0` which is obviously invalid. LBP1 would show a minor visual glitch (no rank at all for the first player, then the second score would continue on from `#1`) and LBP2 would refuse to display the leaderboard entirely.
Simply start calculating ranks from 1, or add 1 to the current index. Both methods are used where it's convenient to do so.
=> Fix score ranks starting at 0

Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameUserResponse.cs, Refresh.GameServer/Endpoints/Game/Levels/LevelEndpoints.cs, Refresh.GameServer/Endpoints/Game/RelationEndpoints.cs, Refresh.GameServer/Types/Levels/Categories/SerializedCategory.cs, Refresh.GameServer/Types/Lists/SerializedFavouriteUserList.cs, Refresh.GameServer/Types/Lists/SerializedFriendsList.cs, Refresh.GameServer/Types/Lists/SerializedList.cs, Refresh.GameServer/Types/Lists/SerializedMinimalFavouriteLevelList.cs, Refresh.GameServer/Types/Lists/SerializedMinimalFavouriteUserList.cs, Refresh.GameServer/Types/Lists/SerializedMinimalLevelList.cs, Refresh.GameServer/Types/Lists/SerializedMinimalLevelResultsList.cs, RefreshTests.GameServer/Tests/Lists/ListTests.cs
A while ago, I wrote the common `SerializedList` class that most serialized objects use for pagination. Turns out this had a pretty significant bug that causes the `hint_start` attribute (the number the game uses to determine how far to skip into the list) to be set to the number of items the page, and it would **not** take into account the current page the user was on.
This means that after the second page, it would keep repeating the second page over and over because it kept returning the same `hint_start `variable.
Simply add a `skip` parameter to all classes extending `SerializedList` so we can appropriately set the hint. In some cases, `hint_star` is not actually entirely necessary, so in those cases we simply re-use the count of items in the list as was the logic before.
=> Fix server incorrectly calculating hint_start

Refresh.GameServer/Authentication/TokenGameUtility.cs
Removed PS4 title ids, removed demos/press showcases/kiosk versions that can't connect online
This information is loosely based off of SerialStation's data, which is kinda inaccurate. I'm not sure how else to find what's missing, but I tried my best to collect everything together in a reasonable way.
=> Try to organize our set of title ids

Refresh.GameServer/Endpoints/Game/ReportingEndpoints.cs
When making a grief report, if a player is outside of the visible area of the screenshot, the game wont supply a rectangle, and the deserializer will leave it null.
Found this yesterday, only happens when `RedirectGriefReportsToPhotos` is enabled, so it would explain why sometimes the screenshots never go through.
=> ReportingEndpoints: Handle player.Rectangle being null

Refresh.GameServer/Types/Report/Rect.cs
This was noticed when doing a grief report of a photo containing a photo containing a photo, it seems that the game sends the rects of every single player in every single photo, and the logic for that seems to break down, and start sending nonsense values
`<screenRect><rect t="4294967236" l="4294967214" b="9" r="109"/></screenRect>`
=> LBP will sometimes send rectangles which are stupendously large.

Refresh.GameServer/Database/GameDatabaseContext.Users.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Request/ApiUpdateUserRequest.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiExtendedGameUserResponse.cs, Refresh.GameServer/Endpoints/Game/ModerationEndpoints.cs, Refresh.GameServer/Services/CommandService.cs, Refresh.GameServer/Types/UserData/GameUser.cs
This allows you to use special tags like `<em>`, `<font>`, `<player>` for advanced text editing.
This is already possible by modifying plan files or by using a proxy to intercept the /filter requests, this option just makes it *much* more accessible to users.
Requires a change in refresh-web.
=> Add option to unescape XML for filter requests.

Refresh.Analyzers/Refresh.Analyzers.csproj, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Request/ApiResetUserPasswordRequest.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameUserResponse.cs, Refresh.GameServer/Importing/Importer.cs, Refresh.GameServer/Importing/Mip/MipHeader.cs, Refresh.GameServer/Types/Activity/ActivityPage.cs, Refresh.GameServer/Types/Matching/Responses/SerializedRoomMatchResponse.cs, Refresh.GameServer/Types/Notifications/GameAnnouncement.cs, Refresh.GameServer/Types/Photos/GamePhotoSubject.cs, Refresh.GameServer/Types/SequentialIdStorage.cs, RefreshTests.GameServer/GameServer/GameServerTest.cs, RefreshTests.GameServer/Tests/ApiV3/LevelApiTests.cs, RefreshTests.GameServer/Tests/Authentication/AuthenticationIntegrationTests.cs, RefreshTests.GameServer/Tests/Middlewares/ApiV2MiddlewareTests.cs, RefreshTests.GameServer/Tests/Middlewares/LegacyAdapterMiddlewareTests.cs
Realm's source generator still generates some nullability warnings (17 as of this PR), but unfortunately we don't have any reasonable control over them. This PR just resolves the warnings that we *can* resolve.
=> Resolve most build warnings

Refresh.GameServer/Extensions/LevelEnumerableExtensions.cs
#333 broke the ability for level authors to view their own sublevels.
In my opinion, it's better to show them wrongly than to hide them wrongly, so let's just revert this for now.
=> Revert "Filter out sub-levels from level results"

Refresh.GameServer/Types/Levels/GameMinimalLevelResponse.cs
Before this patch, you could play a locked level by clicking on it from the level browse list before it loads the full information.
=> Send locked status in minimal response

Refresh.GameServer/Authentication/TokenGame.cs, Refresh.GameServer/Authentication/TokenGameUtility.cs, Refresh.GameServer/Database/GameDatabaseContext.Users.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameUserResponse.cs, Refresh.GameServer/Endpoints/Game/Handshake/AuthenticationEndpoints.cs, Refresh.GameServer/Extensions/LevelEnumerableExtensions.cs, Refresh.GameServer/Services/CommandService.cs, Refresh.GameServer/Services/GuidCheckerService.cs, Refresh.GameServer/Types/UserData/GameUser.cs
Some beta builds can end up posting levels that can crash players playing on mainline versions of the game. For example, a player playing on a deploy build can upload a level that will be registered as an LBP1 level. This causes a hard crash upon loading in LBP1.
This also introduces 2 commands that are __not__ debug commands:
- `/beta`: Switches the token to be `TokenGame.BetaBuild`. Can be used for builds that do not properly identify themselves as beta builds, e.g. deploy.
- `/revoketoken`: Revokes the token, essentially forcing the game to redo the handshake with the server. This can be used to switch away from beta mode, can also just be generally useful.
This was vaguely tested.
=> Add the ability for beta builds to have their own isolated space

Refresh.GameServer/Configuration/ContactInfoConfig.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiContactInfoResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiInstanceResponse.cs, Refresh.GameServer/Endpoints/ApiV3/InstanceApiEndpoints.cs, Refresh.GameServer/RefreshGameServer.cs, RefreshTests.GameServer/GameServer/TestRefreshGameServer.cs
Servers owner can now specify some essential contact information. Primarily we want name and email, and optionally Discord information.
Name and email **requires** support in refresh-web, but Discord can be excluded for now.
=> Allow server owners to specify contact information

Refresh.GameServer/CommandLineManager.cs, Refresh.GameServer/Database/GameDatabaseContext.Registration.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/ApiV3/AuthenticationApiEndpoints.cs, Refresh.GameServer/RefreshGameServer.cs, Refresh.GameServer/Types/UserData/DisallowedUser.cs, RefreshTests.GameServer/Tests/ApiV3/UserApiTests.cs
=> Add ability to block certain users from registering accounts

Refresh.GameServer/Endpoints/Game/PresenceEndpoints.cs, RefreshTests.GameServer/Tests/Presence/PresenceEndpointTests.cs
Implementing this makes Deploy stop spamming us with requests to this endpoint
=> Presence: Implement `/lbp/planetStats/highestSlotId`

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Endpoints/Game/CommentEndpoints.cs, Refresh.GameServer/Endpoints/Game/Levels/LeaderboardEndpoints.cs, Refresh.GameServer/Endpoints/Game/Levels/LevelEndpoints.cs, Refresh.GameServer/Endpoints/Game/RelationEndpoints.cs, Refresh.GameServer/Endpoints/Game/ReviewEndpoints.cs, RefreshTests.GameServer/Tests/Levels/ScoreLeaderboardTests.cs, RefreshTests.GameServer/Tests/Relations/ReviewTests.cs
This de-duplicates a lot of code, and also implements a bunch of currently unimplemented endpoints.
This changes behavior somewhat, but the changes are not important (returning `NotFound` for invalid slot types, rather than `BadRequest`). I can see arguments for both of these being valid to respond with, but its simplest to return NotFound here.
=> Make all our slot endpoints slotType agnostic

Refresh.GameServer/Configuration/GameServerConfig.cs, Refresh.GameServer/Endpoints/ApiV3/ResourceApiEndpoints.cs, Refresh.GameServer/Endpoints/Game/ResourceEndpoints.cs, Refresh.GameServer/Types/Roles/GameUserRole.cs, RefreshTests.GameServer/Tests/Assets/AssetUploadTests.cs
We haven't heard back from the NCMEC yet, so here's a band-aid solution to let people upload things for the time being.
Requires a change to add the new role in refresh-web.
=> Allow new 'trusted' users to upload assets during read-only mode

Refresh.GameServer/Configuration/GameServerConfig.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiInstanceResponse.cs, Refresh.GameServer/Endpoints/ApiV3/InstanceApiEndpoints.cs, Refresh.GameServer/Endpoints/Game/ResourceEndpoints.cs, Refresh.GameServer/Types/Assets/AssetSafetyLevel.cs, RefreshTests.GameServer/Tests/Assets/AssetUploadTests.cs
This PR introduces a new tier for asset safety levels named "SafeMedia". It's intended to represent assets that are images or audio to help administrators single out images during content blocking.
Hopefully, this should replace our need to disable asset uploads on production.
=> Add new "SafeMedia" tier between Safe and PotentiallyUnwanted

Refresh.GameServer/Types/Matching/MatchMethods/FindRoomMethod.cs, RefreshTests.GameServer/Tests/Matching/MatchingTests.cs
This PR makes the following changes
- Don't match players into rooms which won't fit them
- Don't create 3 copies of the room list worst-case. This is just a small optimization
- Select rooms with a weighted distribution, instead of a uniform distribution. This makes "better" rooms (e.g. higher mood) much more likely to be picked.
- Return a proper 404 status code when no rooms are found.
- Dont try to filter by level if the level id is 0 (this is a current bug, since the game very often sends level id of 0)
=> Matching: Heavily refactor our dive-in code

Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs
When the OriginalPublisher was null, but a level was marked as a reupload, it would lead to issues. This PR fixes that.
=> Fix blank OriginalPublisher issues

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseContext.Relations.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiLevelCategoryResponse.cs, Refresh.GameServer/Endpoints/ApiV3/LevelApiEndpoints.cs, Refresh.GameServer/Endpoints/Game/Levels/LevelEndpoints.cs, Refresh.GameServer/Extensions/LevelEnumerableExtensions.cs, Refresh.GameServer/Types/Levels/Categories/ByUserLevelCategory.cs, Refresh.GameServer/Types/Levels/Categories/ContestCategory.cs, Refresh.GameServer/Types/Levels/Categories/CoolLevelsCategory.cs, Refresh.GameServer/Types/Levels/Categories/CurrentlyPlayingCategory.cs, Refresh.GameServer/Types/Levels/Categories/DeveloperLevelsCategory.cs, Refresh.GameServer/Types/Levels/Categories/FavouriteSlotsByUserCategory.cs, Refresh.GameServer/Types/Levels/Categories/HighestRatedLevelsCategory.cs, Refresh.GameServer/Types/Levels/Categories/LevelCategory.cs, Refresh.GameServer/Types/Levels/Categories/MostHeartedLevelsCategory.cs, Refresh.GameServer/Types/Levels/Categories/MostReplayedLevelsCategory.cs, Refresh.GameServer/Types/Levels/Categories/MostUniquelyPlayedLevelsCategory.cs, Refresh.GameServer/Types/Levels/Categories/NewestLevelsCategory.cs, Refresh.GameServer/Types/Levels/Categories/QueuedLevelsByUserCategory.cs, Refresh.GameServer/Types/Levels/Categories/RandomLevelsCategory.cs, Refresh.GameServer/Types/Levels/Categories/SearchLevelCategory.cs, Refresh.GameServer/Types/Levels/Categories/SerializedCategory.cs, Refresh.GameServer/Types/Levels/Categories/TeamPickedLevelsCategory.cs, RefreshTests.GameServer/Tests/Levels/PublishEndpointsTests.cs
Fixes #332, #347
This required a minor category refactor due to how they previously used the accessor and content user interchangeably
=> Hide sub levels from people who didn't publish them

Refresh.GameServer/RefreshGameServer.cs, Refresh.GameServer/Storage/AggregateDataStore.cs, Refresh.GameServer/Storage/DryArchiveConfig.cs, Refresh.GameServer/Storage/DryDataStore.cs
will move AggregateDataStore to bunkum in the the future
=> Support the dry archive's file format as an IDataStore

Dockerfile, docker-compose.yml
Hello! I stumbled across this project while setting up a Project Lighthouse server (and dealing with a lack of documentation or working Docker configuration, eventually ending up with writing my own scripts and a badgering LICENSE VIOLATION warning all over the place), and decided to switch to it from there.
Upon doing so, I was greeted with what I thought was originally a critical error, but quickly resolved to an issue with the unhealthy check:
```
refresh-gameserver  |  ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
refresh-gameserver  |    at Bunkum.Protocols.Http.Socket.SocketHttpListener.ReadRequestIntoContext(Socket client, Stream stream)
refresh-gameserver  |    --- End of inner exception stack trace ---
refresh-gameserver  |    at …
```
=> Make the Docker unhealthy check a little more portable

Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs, Refresh.GameServer/Endpoints/Game/Levels/LevelEndpoints.cs
This fixes LBP3 which will complain about "upgrading" the level when the level ID is reused.
=> "hash" hashed level hashes to generate unique level IDs

Refresh.GameServer/Endpoints/ApiV3/ActivityApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiV3/Admin/AdminUserApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiV3/AuthenticationApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiV3/LeaderboardApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiV3/LevelApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiV3/MatchingApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiV3/NotificationApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiV3/PhotoApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiV3/ReviewApiEndpoints.cs, Refresh.GameServer/Extensions/RequestContextExtensions.cs
- Automatically determine `api` parameter
Prevents us from mistakenly setting `api` to false in an API route and having the wrong behaviour be applied.
- Replace the `maxCount` parameter with a constant
We weren't actually overriding the default of 100 anywhere.
- Properly use `int.TryParse`
Before, we were checking against the default value. Why? I don't know. Now we use the boolean result as we should have been doing.
=> GetPageData slight refactor

Refresh.GameServer/Endpoints/ApiV3/LevelApiEndpoints.cs
I keep hitting this myself, so I bet others will at some point
=> Warn API caller if route not specified for `/levels/{route}` endpoint

Refresh.GameServer/Database/GameDatabaseContext.Registration.cs, Refresh.GameServer/Database/GameDatabaseContext.Tokens.cs, Refresh.GameServer/Endpoints/ApiV3/AuthenticationApiEndpoints.cs, Refresh.GameServer/Workers/ExpiredObjectWorker.cs
- [Make registrations expire in 1 hour](https://github.com/LittleBigRefresh/Refresh/commit/75a777670f85ddbff1fd668d1d8906c23b1a98c7)
Hopefully shouldn't backfire. The goal is to help users who accidentally signed up with the wrong usernames. Should result in less admin intervention.
- [Remove tokens when expired](https://github.com/LittleBigRefresh/Refresh/commit/5d1bdab6fc22b88973014dc258ff7ca4f5b29aaf)
We were originally storing these for historical purposes, but we never used this data.
The first time this runs, it will take a very long time (roughly 10-30 minutes) on production as we don't do any batching when removing these tokens from Realm, but it won't be an issue as new tokens expire. **This will not block startup. This operation will run in the background.**
Closes #418.
- …
=> Tweaks to object expiry

Refresh.GameServer/Configuration/GameServerConfig.cs, Refresh.GameServer/Database/GameDatabaseContext.Statistics.cs, Refresh.GameServer/Endpoints/ApiV3/InstanceApiEndpoints.cs, Refresh.GameServer/RefreshGameServer.cs, Refresh.GameServer/Services/RequestStatisticTrackingService.cs, Refresh.GameServer/Workers/RequestStatisticSubmitWorker.cs
This massively improves performance of ***all*** requests by incrementing the request counters in a background thread every 5 seconds, as opposed to the previous solution of incrementing by one upon every request.
Since we are no longer committing to Realm every request, we also remove the ability to disable request tracking as there is no performance penalty for having it on.
This brings all requests down from roughly an average of 8-16ms all the way down to 1-2ms. For large swarms of requests such as a level downloader grabbing assets from us at high speeds, this can reduce write speeds of up to 30mb/s to practically nothing, as well as reducing peak request times from 130ms to the same 1-2ms.
=> Move request tracking submission to background worker

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseContext.Users.cs, Refresh.GameServer/Endpoints/Game/Handshake/MetadataEndpoints.cs
This introduces a few changes to make this possible:
- We add the ability to find users by their usernames without requiring case sensitivity. This is controlled by a new optional parameter in `GetUserByUsername`. This is free to be used in other areas of the codebase when necessary, but for this PR it's just used in Search.
- I changed the ordering to sort by CR. Should hopefully improve ranking and help people find what they're looking for, e.g. the skateboard extreme everyone plays instead of the one that got reuploaded for the 7892364th time 2 minutes ago.
=> Search by publisher

Refresh.GameServer/Workers/CoolLevelsWorker.cs
- Removes 15 CR bonus to new levels if they are reuploads
- Bumps the team pick bonus from 10 to 50
- Changes time required to fully decay from 3 months to 2 months
- Only reward 0.1 positive score per unique play (was 1 point before)
- Only apply 75% of the calculated negative score
- Adjust reward for hearts to 10 positive score
- Add a reward for a good ratio between plays and yays
=> Cool Levels May 2024 Rebalance

Refresh.GameServer/Endpoints/ApiV3/AuthenticationApiEndpoints.cs
1 per day is *way* too strict, we need at least 2, so people actually hit the "account already registered" flag
So i thought 5 per hour is a reasonable count
=> Up rate limit for registrations

Refresh.GameServer/Database/GameDatabaseContext.Activity.cs, Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseContext.Photos.cs, Refresh.GameServer/Database/GameDatabaseContext.Relations.cs, Refresh.GameServer/Database/GameDatabaseContext.Users.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/Game/CommentEndpoints.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameUserResponse.cs, Refresh.GameServer/Types/Comments/GameComment.cs, Refresh.GameServer/Types/UserData/GameUser.cs, RefreshTests.GameServer/Tests/Levels/ScoreLeaderboardTests.cs, RefreshTests.GameServer/Tests/Relations/QueueTests.cs
This PR replaces all the backlinks in GameUser with equivalents using `GameDatabaseContext`. Doing this does not require any migrations, it seems.
Tested with unit tests and API, but the game hasn't been tested. I'd recommend doing so.
It's worth noting that these are all cherry-picked from the postgres branch.
=> Remove backlinks from GameUser and GameComment

Refresh.GameServer/Database/GameDatabaseContext.Comments.cs, Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseContext.Photos.cs, Refresh.GameServer/Database/GameDatabaseContext.Relations.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/Levels/ApiGameLevelResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/Users/ApiExtendedGameUserResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/Users/ApiGameUserResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/Users/ApiGameUserStatisticsResponse.cs
Closes #515.
Ideally I would have included level statistics in a new Statistics object like I've done for users for organization purposes, but there are already statistics present in ApiGameLevelResponse and I don't want to have them split up.
Something to consider for APIv4 if we ever consider jumping from v3.
=> Implement various API extensions

Refresh.GameServer/Database/GameDatabaseContext.Leaderboard.cs, Refresh.GameServer/Endpoints/ApiV3/Admin/AdminLeaderboardApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiV3/Admin/AdminLevelApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiV3/LeaderboardApiEndpoints.cs, RefreshTests.GameServer/Tests/Levels/ScoreModerationTests.cs
Also allows quickly wiping every score set by a user in an incredibly inefficient way thanks to Realm.
Closes #145.
=> Ability to delete scores via the API

Refresh.GameServer/Database/GameDatabaseContext.Users.cs
30 days seems to be too long; our server is [reporting 1043 active users](https://lbp.littlebigrefresh.com/api/v3/statistics) which is simply not even close to how many people are actually playing.
We'll see how well a week works.
=> Shorten time frame required to be considered 'active' to 7 days

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs
=> Fix `GetTotalLevelsPublishedByUser` returning global level count

Refresh.GameServer/Database/Activity/GameDatabaseContext.Activity.cs, Refresh.GameServer/Database/Activity/GameDatabaseContext.ActivityRead.cs, Refresh.GameServer/Database/Activity/GameDatabaseContext.ActivityWrite.cs, Refresh.GameServer/Database/GameDatabaseContext.Assets.cs, Refresh.GameServer/Database/GameDatabaseContext.Comments.cs, Refresh.GameServer/Database/GameDatabaseContext.Contests.cs, Refresh.GameServer/Database/GameDatabaseContext.Leaderboard.cs, Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseContext.Notifications.cs, Refresh.GameServer/Database/GameDatabaseContext.Photos.cs, Refresh.GameServer/Database/GameDatabaseContext.Registration.cs, Refresh.GameServer/Database/GameDatabaseContext.Relations.cs, Refresh.GameServer/Database/GameDatabaseContext.Statistics.cs, Refresh.GameServer/Database/GameDatabaseContext.Tokens.cs, Refresh.GameServer/Database/GameDatabaseContext.Users.cs, Refresh.GameServer/Database/GameDatabaseContext.cs, Refresh.GameServer/Database/RealmDbSet.cs
- Introduces `RealmDbSet` class that provides... 'polyfills' I guess... for write operations on the realm, e.g. `this._realm.Add<T>`.
- Instead of using `this._realm.All<T>`, you now obtain queryables from the main class, e.g. `this.GameUsers` for `GameUser`.
- Write blocks now point to an easily replaceable function as discussed [on Discord](https://discord.com/channels/1049223665243389953/1049225857350254632/1252437212855930970).
Usage of `this._realm` is now **banned** outside of the main `GameDatabaseContext` class and `RealmDbSet` to keep source compatibility with EF.
I recommend a commit-by-commit review (and not looking at any of the `GameDatabaseContext.whatever.cs` files) for this one.
=> Minimize calls to `this._realm` for source compatibility with Entity Framework

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Endpoints/Game/Levels/PublishEndpoints.cs, RefreshTests.GameServer/Tests/Levels/PublishEndpointsTests.cs
This should curb the reuploads on the official instance by a small amount. There isnt a good reason for a person to want to do this in a circumstance other than spamming/uploading a duplicate level. This is something we'd want to do after the dry archive import anyway, so might as well do it now since its very little code, and helps an immediate issue.
=> Prevent users from re-publishing a level twice.

Refresh.GameServer/Database/GameDatabaseContext.Photos.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Types/Photos/GamePhoto.cs, Refresh.GameServer/Types/Photos/GamePhotoSubject.cs
Instead of storing a list of `GamePhotoSubject`s as `IEmbeddedObject`s under `GamePhoto`, I took the fields of `GamePhotoSubject` and unrolled them to 4 (not arbitrary, this represents the max number of players you may have in an LBP lobby) sets of fields under `GamePhoto`.
This makes things sloppy when handling model code, but does make it compatible with Postgres. I've done my best to mask this behind the existing `Subjects` list, which I've repurposed to be a getter/setter that emulates the original behavior, while still keeping the `GamePhotoSubject` class for compatibility/ease of use with existing code.
I've included migrations which are a little sketchy, but they seem to work fine on my end. Uploading new photos is untested in-game but it uses mostly the same code as the migrations …
=> Remove `GamePhotoSubject` from database schema

Refresh.GameServer/Endpoints/Game/Levels/LeaderboardEndpoints.cs, Refresh.GameServer/Types/Lists/SerializedScoreList.cs, RefreshTests.GameServer/Tests/Levels/ScoreLeaderboardTests.cs
Closes #498
Previously when serializing scores, the scores' ranks would not be set properly after the first page. This is because the game depends on a `Rank` value being set correctly server-side.
The server-side was failing to take in the `skip` query parameter when setting the Rank value, so every page would begin at rank #1.
To fix, pass it in when making the `SerializedScoreList`.
=> Fix incorrect rank when paginating scores

.idea/.idea.Refresh/.idea/git_toolbox_blame.xml, Refresh.GameServer/Endpoints/ApiV3/Admin/AdminLevelApiEndpoints.cs, Refresh.GameServer/Types/Roles/GameUserRole.cs, RefreshTests.GameServer/TestContext.cs, RefreshTests.GameServer/Tests/ApiV3/EditApiTests.cs, RefreshTests.GameServer/Tests/Levels/ContestTests.cs
Implemented as described in #492.
Includes a bonus refactor to `TestContext` to make making users with roles from within tests a bit easier.
=> Refactor CreateUser to accept a role to set, implement curator role

Refresh.GameServer/Configuration/GameServerConfig.cs, Refresh.GameServer/Endpoints/Game/MatchingEndpoints.cs, Refresh.GameServer/Services/MatchService.cs, Refresh.GameServer/Types/Matching/MatchMethods/CreateRoomMethod.cs, Refresh.GameServer/Types/Matching/MatchMethods/FindRoomMethod.cs, Refresh.GameServer/Types/Matching/MatchMethods/IMatchMethod.cs, Refresh.GameServer/Types/Matching/MatchMethods/UpdatePlayersInRoomMethod.cs, Refresh.GameServer/Types/Matching/MatchMethods/UpdateRoomDataMethod.cs, RefreshTests.GameServer/Tests/Matching/MatchingTests.cs
Printing the room state out always helps a lot with debugging when people state that "dive in doesn't work". 
Often by the time someone responds "can you take a capture of the API room output", the room state has changed enough where it's not as helpful, the API also doesn't expose info like NAT type or build version. This change makes sure that we can easily see exactly what the server was seeing when it filtered down the rooms, and can narrow down why no rooms were found.
If the extra noise does become a problem in the future when we grow and have many rooms, I have made the dump a config option, so that it can be easily disabled/re-enabled when needed.
The level ID search changes should also fix some issues people have been having with dive in.
=> FindRoomMethod: Fix level ID search & always print room state

Refresh.Common/Extensions/MemoryStreamExtensions.cs, Refresh.GameServer/Extensions/MemoryStreamExtensions.cs, Refresh.GameServer/Middlewares/DigestMiddleware.cs, Refresh.GameServer/Refresh.GameServer.csproj, Refresh.HttpsProxy/Config/ProxyConfig.cs, Refresh.HttpsProxy/Middlewares/DigestMiddleware.cs, Refresh.HttpsProxy/Middlewares/ProxyMiddleware.cs, Refresh.HttpsProxy/Program.cs, Refresh.HttpsProxy/Refresh.HttpsProxy.csproj, Refresh.sln
This adds a simple proxy capable of forwarding LBP3 traffic on ports 10061 (HTTPS) and 10060 (HTTP) to another gameserver, it also overrides the original server's digest, allowing clients with non-patched digest keys to connect without the actual gameserver having to support the proxied game's digest.
=> Add Refresh.HttpsProxy

Refresh.GameServer/Types/Matching/MatchMethods/FindRoomMethod.cs
idk how i messed this logic up so bad the first go around, but this makes it actually print, and makes 404 returns happen even if debug logging was disabled
i made it always log *something* in case of a failed match, since we do that with successful matches anyway
=> Fix room logging code and 404 return

Refresh.GameServer/RefreshGameServer.cs, Refresh.GameServer/Types/Data/DataContextService.cs, Refresh.GameServer/Workers/CoolLevelsWorker.cs, Refresh.GameServer/Workers/DiscordIntegrationWorker.cs, Refresh.GameServer/Workers/ExpiredObjectWorker.cs, Refresh.GameServer/Workers/IWorker.cs, Refresh.GameServer/Workers/PunishmentExpiryWorker.cs, Refresh.GameServer/Workers/RequestStatisticSubmitWorker.cs, Refresh.GameServer/Workers/WorkerManager.cs, RefreshTests.GameServer/TestContext.cs, RefreshTests.GameServer/Tests/Workers/PunishmentExpiryTests.cs
- Refactor workers to use DataContext
This makes Workers compatible with `IDataConvertable`. Should help us expand Workers in the future as a side bonus. Admittedly, this causes a bit of jank particularly in tests and having to store the match service, but I think it should be okay.
- Convert to API data types in DiscordIntegrationWorker
This allows us to get the same results as the API (e.g. applying PSP path, cropped asset URLs, etc.) for free, avoiding code duplication. Closes #574.
=> Worker + Discord Webhook refactor

Refresh.GameServer/Configuration/IntegrationConfig.cs, Refresh.GameServer/Documentation/RefreshDocumentationGenerator.cs, Refresh.GameServer/Endpoints/ApiV3/ApiTypes/Errors/ApiValidationError.cs, Refresh.GameServer/Endpoints/ApiV3/AuthenticationApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiV3/ResourceApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiV3/UserApiEndpoints.cs, Refresh.GameServer/Endpoints/Game/AnnouncementEndpoints.cs, Refresh.GameServer/Endpoints/Game/CommentEndpoints.cs, Refresh.GameServer/Endpoints/Game/Levels/LeaderboardEndpoints.cs, Refresh.GameServer/Endpoints/Game/Levels/PublishEndpoints.cs, Refresh.GameServer/Endpoints/Game/MatchingEndpoints.cs, Refresh.GameServer/Endpoints/Game/ModerationEndpoints.cs, Refresh.GameServer/Endpoints/Game/PhotoEndpoints.cs, Refresh.GameServer/Endpoints/Game/ReportingEndpoints.cs, Refresh.GameServer/Endpoints/Game/ResourceEndpoints.cs, Refresh.GameServer/Endpoints/Game/ReviewEndpoints.cs, Refresh.GameServer/Endpoints/RequireEmailVerifiedAttribute.cs, Refresh.GameServer/Refresh.GameServer.csproj, Refresh.GameServer/Services/RoleService.cs, Refresh.GameServer/Services/SmtpService.cs, RefreshTests.GameServer/GameServer/TestRefreshGameServer.cs
- Adds a new `[RequireEmailVerified]` attribute that can be applied to endpoints.
This uses the same system as `[MinimumRole]`, where the endpoint will not be executed at all if the user does not have a verified email address. It will simply return 401 Unauthorized instead.
- Hijacks `/announce` when the user doesn't have an email address, informing them on how to verify.
- Does a basic DNS check against the email domain, preventing users from registering/editing their email if the email server doesn't actually exist.
To make this trivial, this brings in a NuGet package called [`DnsClient`](https://dnsclient.michaco.net/). It's also optional, you can disable this functionality behind a flag in `IntegrationConfig`.
=> Enforce email verification

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseContext.Relations.cs, Refresh.GameServer/Database/GameDatabaseContext.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/Levels/ApiGameLevelResponse.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs, Refresh.GameServer/Endpoints/Game/Handshake/MetadataEndpoints.cs, Refresh.GameServer/Endpoints/Game/RelationEndpoints.cs, Refresh.GameServer/Types/Levels/Categories/ByTagCategory.cs, Refresh.GameServer/Types/Levels/Categories/CategoryService.cs, Refresh.GameServer/Types/Levels/GameMinimalLevelResponse.cs, Refresh.GameServer/Types/Levels/Tag.cs, Refresh.GameServer/Types/Relations/TagLevelRelation.cs
This is the first part of #260, implementing in-game level tagging for LBP1.
This also exposes an APIv3 endpoint for getting a list of levels by tag, and also shows the tags of a level on API level responses.
=> Implement level tagging

Refresh.GameServer/Endpoints/Game/MatchingEndpoints.cs, Refresh.GameServer/Services/MatchService.cs, Refresh.GameServer/Types/Matching/GameRoom.cs, Refresh.GameServer/Types/Matching/IRoomAccessor.cs, Refresh.GameServer/Types/Matching/MatchMethods/CreateRoomMethod.cs, Refresh.GameServer/Types/Matching/MatchMethods/FindRoomMethod.cs, Refresh.GameServer/Types/Matching/MatchMethods/UpdatePlayersInRoomMethod.cs, Refresh.GameServer/Types/Matching/MatchMethods/UpdateRoomDataMethod.cs, Refresh.GameServer/Types/Matching/RoomAccessors/InMemoryRoomAccessor.cs, Refresh.GameServer/Types/Matching/SerializedRoomData.cs
In the future, we're going to ensure the user is on the latest game version via enforcing user agent (old builds will be sent to `BetaBuild`). Tracking `BuildVersion` seems to cause issues as shown [here](https://discord.com/channels/1049223665243389953/1049225857350254632/1266966969697960037) so let's just stop tracking/comparing against that for now.
=> Ignore game build version when matching

Refresh.GameServer/Database/GameDatabaseContext.Leaderboard.cs, Refresh.GameServer/Endpoints/Game/Levels/LeaderboardEndpoints.cs, Refresh.GameServer/Types/Scores/FriendScoresRequest.cs
The query here is extraordinarily slow (~10s in Debug mode on my machine, with a warmed up JIT). But leaving it as a 404 causes the game to wait a full 30 seconds between requests, so even though these requests are serial in LBP, its still faster for users in the end to have it implemented.
We can optimize the query after Postgres gets in.
=> Implement friend leaderboards

Refresh.GameServer/Workers/CoolLevelsWorker.cs
This causes cool levels to *much* more aggressively favor levels from the past month or two, and past that the decay quickly converges with 0. Removing the bottom limit makes sure that cool rating will always go down, even if an older level gets popular again.
Cool Levels after this PR:
=> CoolLevelsWorker: Use an exponential decay function for CR

Refresh.HttpsProxy/Program.cs
Since we pass the `BunkumServer` into the `Initialize` function to avoid a closure allocation, we can use this to our advantage and only have one function to set up both servers.
=> Reduce code duplication when initializing Refresh.HttpsProxy

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/Levels/ApiGameLevelResponse.cs, Refresh.GameServer/Types/Levels/GameLevel.cs
Some improvements suggested by CrankyLandlord of the curators team. Closes #584.
- Always retain team pick status when updating level
- Store date of team picks instead of just that the level is team picked
=> Team Picks refactor

Refresh.Common/Refresh.Common.csproj, Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/Levels/ApiGameLevelResponse.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Request/GameLevelRequest.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs, Refresh.GameServer/Endpoints/Game/Levels/PublishEndpoints.cs, Refresh.GameServer/Refresh.GameServer.csproj, Refresh.GameServer/RefreshContext.cs, Refresh.GameServer/Types/Levels/Categories/AdventureCategory.cs, Refresh.GameServer/Types/Levels/Categories/CategoryService.cs, Refresh.GameServer/Types/Levels/GameLevel.cs, Refresh.GameServer/Types/Levels/GameMinimalLevelResponse.cs, Refresh.GameServer/Types/Levels/SerializedLevelResources.cs, Refresh.HttpsProxy/Refresh.HttpsProxy.csproj, RefreshTests.GameServer/Tests/Levels/PublishEndpointsTests.cs
Pretty straight-forward. Includes a category that only shows adventures levels as a side-bonus.
This also checks against the `GameAsset` type to see if the RootLevel is the expected type, returning an error if so. This only happens if the `GameAsset` is available; the only case where this would happen would be when re-uploading an adventure/level from the dry archive.
=> Add support for adventures

Refresh.GameServer/Services/MatchService.cs, Refresh.GameServer/Types/Matching/MatchMethods/FindRoomMethod.cs, Refresh.GameServer/Types/Matching/Responses/SerializedStatusCodeMatchResponse.cs, Refresh.GameServer/Types/Matching/SerializedRoomData.cs, RefreshTests.GameServer/Tests/Matching/MatchingTests.cs
=> Dive in by level fix

Refresh.GameServer/CommandLineManager.cs, Refresh.GameServer/Database/GameDatabaseContext.Users.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs, Refresh.GameServer/RefreshGameServer.cs
Helps with moderating those who are re-uploading story levels. This is only accessible with the CLI but in the future we may want to allow curators to do this. For now I just want curators to ask.
=> Implement reupload marking for all levels of a user

Refresh.GameServer/Database/GameDatabaseContext.cs, Refresh.GameServer/Database/ISequentialId.cs, Refresh.GameServer/Types/Levels/GameLevel.cs, Refresh.GameServer/Types/Photos/GamePhoto.cs, Refresh.GameServer/Types/Reviews/GameReview.cs
=> Fix incorrect SequentialIdStorage migration behavior

Refresh.GameServer/Database/GameDatabaseContext.Relations.cs, Refresh.GameServer/Workers/CoolLevelsWorker.cs
More anti-sackattack1 and pro-crankylandlord propaganda.
In English, this means that people who heart their own levels won't be able to gain CR from doing so.
=> Exclude level author's relations from cool levels

Refresh.GameServer/Database/GameDatabaseContext.Photos.cs, Refresh.GameServer/Endpoints/ApiV3/Admin/AdminPhotoApiEndpoints.cs
=> Add admin photo moderation endpoints

Refresh.GameServer/Database/GameDatabaseContext.Assets.cs
Prevents tons of SOH allocations (apparently up to 121.1 MB even locally) and makes things (more than) a tiny bit more efficient. Should be the same logic.
=> Optimize `GetConvertedType` by using a server-side query

Refresh.GameServer/Endpoints/ApiV3/ResourceApiEndpoints.cs, Refresh.GameServer/Importing/ImageImporter.cs, Refresh.GameServer/Importing/Importer.cs, Refresh.GameServer/RefreshGameServer.cs, Refresh.GameServer/Storage/RemoteRefreshDataStore.cs
Implemented as discussed on [Discord](https://discord.com/channels/1049223665243389953/1049225857350254632/1270832582501597378).
For ease of testing, use the included new `IDataStore` named `RemoteRefreshDataStore` to use prod as a storage backend, then look at reuploads from the archive. Notice that they now have icons.
=> Allow conversion of assets not in the database to images

Refresh.GameServer/Endpoints/Game/ModerationEndpoints.cs
If a user is playing on an unverified account, they wont be able to edit text in magic mouths on their moon right now, which is definitely not the intended behaviour. 
So we allow unverified `/filter` requests, but block commands from being run.
=> Allow unverified users to access `/filter`, but still blocking commands

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, RefreshTests.GameServer/Tests/ApiV3/EditApiTests.cs
=> Don't update level modification date if the root level has not changed

Refresh.GameServer/Database/GameDatabaseContext.Contests.cs, Refresh.GameServer/Types/Levels/Categories/ContestCategory.cs, RefreshTests.GameServer/Tests/Levels/ContestTests.cs
Right now, our contest category is empty, but people still care about #LBWSBR. This makes it so that the contest category will *always* have levels from that contest, despite the fact it's over.
=> Show levels from the last active contest after a contest has ended

Refresh.GameServer/Database/GameDatabaseContext.Tokens.cs, Refresh.GameServer/Endpoints/ApiV3/AuthenticationApiEndpoints.cs
I tried to find the Discord conversation behind this, but I couldn't. At some point it was discussed that `ApiRefresh` tokens should reset themselves when used, so no re-login is required ever.
Turns out it was never implemented like this, so users are forced to re-authenticate manually every month as their refresh token expires every month, which is why the website randomly claims that your session has expired. It's not a bug as I thought, it's just... we're stupid.
This PR fixes that.
=> Reset token expiry date when using a refresh token

Refresh.GameServer/CommandLineManager.cs, Refresh.GameServer/RefreshGameServer.cs
From an idea I had after a frustrating email conversation. The idea is that if I want to verify someone is an account-holder (such as over Discord or via an untrusted email) I can send them a code, and ask them to retrieve it for me.
If the code matches with the one I sent then I can proceed with whatever action they're asking for.
To achieve this, I just use the existing notifications infrastructure with the same code generation from email verification.
=> Add ability for admins to ask users for verification codes

Refresh.GameServer/Database/GameDatabaseContext.Relations.cs
Uses the level's publish date. The ideal solution would be storing a timestamp on `QueueLevelRelation` and `FavouriteLevelRelation` but I'm so fucking tired of writing Realm migrations. Also I could have sworn I did this already.
=> Improve ordering of getting favourite/queued levels

Refresh.GameServer/Database/GameDatabaseProvider.cs
Doing all these loops even when there's no work wastes a lot of time, so lets skip them if necessary
=> Optimize realm migrations

Refresh.GameServer/Configuration/IntegrationConfig.cs, Refresh.GameServer/Endpoints/ApiV3/ApiTypes/Errors/ApiModerationError.cs, Refresh.GameServer/Endpoints/ApiV3/ResourceApiEndpoints.cs, Refresh.GameServer/Endpoints/Game/PhotoEndpoints.cs, Refresh.GameServer/RefreshContext.cs, Refresh.GameServer/RefreshGameServer.cs, Refresh.GameServer/Services/AipiService.cs, Refresh.GameServer/Services/DiscordStaffService.cs, Refresh.GameServer/Services/ImportService.cs
Rough port from DO code to integrate AI image scanning into Refresh. This should help reduce the photo endpoint abuse we've been seeing from DT, while using the same existing infrastructure that works incredibly well.
This does not scan every uploaded texture as this would increase server load significantly. It will only scan under certain circumstances:
- for uploaded photos
- for images uploaded via the API
This also brings in the option to automatically restrict users who upload images with banned tags if configured. This will be left off on production while I gauge if this is going to false-flag for normal non-abuse activity.
Oh, this also introduces support for a staff-only webhook. This could be used for a non-persisted audit log if we wanted to use that as a solution for #565.
=> Introduce integrations with AIPI for automated content scanning

Refresh.GameServer/Endpoints/ApiV3/AuthenticationApiEndpoints.cs
People aren't grasping the wording we currently have, there are many wrong interpretations of the current wording, so I've tried to clear up some of the common misunderstandings people have.
- The phrasing of a "queue" implies to some the need to wait. Lets not use that wording when it comes to describing the system. Lets just call it "account activation", since to a layperson, the extra details about how "its not *actually* an account yet" aren't necessary to know. All they need to know is that they cannot log in on the site until their account is activated.
- We weren't explicit enough that you need to access online features, not just "start playing", which doesn't *always* work, since the game won't autoconnect some of the time.
- Some people misunderstood "within the next hour", so …
=> Clarify regstration queue message

.github/workflows/docker.yml, HttpsProxy.Dockerfile, PresenceServer.Dockerfile, docker-compose.yml, scripts/docker-entrypoint.sh
Closes #558
Closes #658
The configurations for `Refresh.PresenceServer` and `Refresh.HttpsProxy` will be invalid on startup but it's expected that you adjust the compose files and the config files as you normally would with a Bunkum installation. In the compose file, I've marked them with profiles to disable those containers by default.
=> Add Docker images for HttpsProxy and PresenceServer

Refresh.GameServer/Middlewares/PresenceAuthenticationMiddleware.cs
Apparently I messed up when doing a simple refactor in review, and broke the authentication middleware. Currently, the presence server is unable to talk to `Refresh.GameServer`.
=> Fix typo in PresenceAuthenticationMiddleware

Refresh.GameServer/Database/Activity/GameDatabaseContext.Activity.cs, Refresh.GameServer/Endpoints/ApiV3/ActivityApiEndpoints.cs, Refresh.GameServer/Endpoints/Game/ActivityEndpoints.cs, Refresh.GameServer/Types/Activity/ActivityPage.cs
Also cleans up some naming to make things more clear.
=> Implement APIv3/Game endpoints for getting events by a user

Refresh.GameServer/Endpoints/Game/ReviewEndpoints.cs, Refresh.GameServer/Types/Reviews/SerializedGameReview.cs
Fixes issue #656 and additionally also corrects a method's name (see the changes below)
=> Fix bug where reviews would always contain your own level rating instead of that of the reviewer's

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Endpoints/ApiV3/Admin/AdminLevelApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Request/ApiSetLevelAuthorRequest.cs
This merge request adds an admin endpoint for changing a level's author. You should be able to do this:
```
POST admin/levels/id/12345/setAuthor
{
"authorName": "ritchie"
}
```
This would change the level with ID `12345`'s author to the user named `ritchie`. Both the level and user must actually exist in the database, otherwise you'll get a 404.
If you try to change the author of a level that has an `OriginalAuthor` value set on it, this value gets unset. This effectively addresses issue #409 .
I haven't actually tested this, I don't have a game patched and adding UI for this in refresh-web isn't my skillset. But it compiles. What could go wrong?
=> Add API support for changing a level's author as an admin

Refresh.GameServer/Endpoints/Game/CommentEndpoints.cs
This lets users comment under levels without a publisher, like story levels, while also conveniently fixing a warning.
=> Fix being unable to comment under publisherless levels

Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Request/GameLevelRequest.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs, Refresh.GameServer/Types/Levels/GameLevel.cs, Refresh.GameServer/Types/Levels/GameMinimalLevelResponse.cs
This implements getting, saving and returning to the game whether a level "requires" a move controller to play, closing issue #680
=> Move controller requirement tracking

Refresh.GameServer/Types/Levels/GameMinimalLevelResponse.cs
Fixes that bug where versus/cutscene levels would only show their badges in-game in certain cases
Closes #397
=> Include level type in GameMinimalLevelResponse

Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs, Refresh.GameServer/Endpoints/Game/ReviewEndpoints.cs
Include the user's review in GameLevelResponse to let the game be able to autofill the user's review if they go edit it. This PR also implements updating the user's level rating when they upload/update their review.
=> Include user's own review in GameLevelResponse, update level rating alongside review

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseContext.Relations.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Types/Relations/FavouriteLevelRelation.cs, Refresh.GameServer/Types/Relations/FavouriteUserRelation.cs, Refresh.GameServer/Types/Relations/QueueLevelRelation.cs, Refresh.GameServer/Types/Relations/RateReviewRelation.cs, Refresh.GameServer/Types/Relations/TagLevelRelation.cs
This one adds timestamps to certain relations to then use some of them to sort hearted levels, queued levels and hearted users by newest first. Also took the opportunity to have levels by users get sorted by most recently updated first.
=> Level and user sorting improvements

Refresh.GameServer/Database/GameDatabaseContext.Photos.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs, Refresh.GameServer/Endpoints/Game/PhotoEndpoints.cs
In-game, show all photos taken in a level aswell as photos taken by the level publisher. These photos get sorted by most recently taken first; and instead of comparing level IDs to get them, compare their level references instead to prevent photos from showing under levels they were not taken in.
=> Show photos taken in levels

Refresh.GameServer/Database/GameDatabaseContext.Relations.cs, Refresh.GameServer/Database/GameDatabaseContext.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Database/RealmDbSet.cs, Refresh.GameServer/Extensions/DbSetExtensions.cs, Refresh.GameServer/Extensions/RealmObjectExtensions.cs, Refresh.GameServer/GlobalUsings.cs, Refresh.GameServer/Refresh.GameServer.csproj, Refresh.sln, RefreshTests.GameServer/RefreshTests.GameServer.csproj
This introduces a new `DebugPostgres` configuration in the solution to facilitate working on Postgres on the main development branch. The idea is that this can be worked on iteratively, while not having the branch rot like the previous two efforts of working on Postgres.
I also did some work as an example on how Realm and Postgres should co-exist, leveraging ifdefs and `global using`s to prevent too much ifdef spam at the top of files. Unfortunately I do have to duplicate the list of `DbSet`s in `GameDatabaseContext`. I tried defining `DbSet` as `RealmDbSet<T>` to mitigate this but C#'s preprocessor can't handle generics.
That sounds weird I know, but this PR is certainly **not** a full implementation, merely a couple steps in that direction. This is so relatively small PRs can be made. …
=> Add solution configuration for Postgres implementation development

Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameUserResponse.cs
Forgot to mention before: this closes issue #674
=> Show users' profile pins in-game

.idea/.idea.Refresh/.idea/AndroidProjectSystem.xml, Refresh.GameServer/Endpoints/Game/Handshake/AuthenticationEndpoints.cs
=> Properly log user agent when patchwork version is invalid

Refresh.Core/Configuration/GameServerConfig.cs, Refresh.Core/Types/Matching/MatchMethods/FindRoomMethod.cs, Refresh.Interfaces.Game/Endpoints/Handshake/MetadataEndpoints.cs
Setting `EnableDiveIn` in network_settings.nws seems to have no effect in LBP2 but I think that should be fine.
=> Ability to properly disable dive-in

Refresh.Core/Configuration/DatabaseConfig.cs, Refresh.Core/RefreshContext.cs, Refresh.Database/Configuration/EmptyDatabaseConfig.cs, Refresh.Database/Configuration/IDatabaseConfig.cs, Refresh.Database/GameDatabaseContext.cs, Refresh.Database/GameDatabaseProvider.cs, Refresh.GameServer/RefreshGameServer.cs, RefreshTests.GameServer/GameServer/TestDatabaseConfig.cs, RefreshTests.GameServer/GameServer/TestGameDatabaseContext.cs
This can be done with either of the following methods:
- Using the `POSTGRES_CONNECTION_STRING` environment variable
- Writing it to `db.json`
This refactors a bit of the database initialization code to make this possible.
On Realm builds, this creates the new config file but has no effect
=> Allow specifying the connection string for Postgres

Refresh.Core/Storage/DryArchiveConfig.cs, Refresh.GameServer/RefreshGameServer.cs
For testing on https://test.lbpbonsai.com
=> Temporarily add option to enable `RemoteRefreshDataStore` in `DebugPostgres` builds

Refresh.Database/Models/Users/GameUser.cs, Refresh.GameServer/Authentication/GameAuthenticationProvider.cs
Previously, Realm would share returned users or presumably operate with magic.
The assumption that `RateLimitUserId` would be held for every GameUser no longer holds true with Postgres/EF, so make it work with Bunkum as intended.
I highly suspect rate-limiting was never working properly.
=> Fix rate-limiting logic applying globally for every user

Refresh.Core/Storage/DownloadingDataStore.cs, Refresh.GameServer/RefreshGameServer.cs
On production the DataStore for the dry archive is mounted on an NFS. This can sometimes mean requests that depend on the dry archive can take a few seconds to complete due to some IO bottlenecks when requesting many assets at once.
I believe this is mostly due to the sheer size of the directories we're pulling from, but I'm not entirely certain.
Either way, this introduces a new datastore that looks at what assets have been requested and copies them to the primary data store (in our case, `FileSystemDataStore`) if there are 3 or more 'hits' to that asset. The idea is that if a asset is only requested once, then we don't need to download it, else we end up just storing the entire dry archive. However, if it's requested more than a few times it's probably worth downloading.
The number of …
=> Add `DownloadingDataStore` to help with common archived assets

Refresh.Common/Constants/LevelPrefixes.cs, Refresh.Database/GameDatabaseContext.Levels.cs, Refresh.Interfaces.Game/Endpoints/Levels/PublishEndpoints.cs, RefreshTests.GameServer/TestContext.cs, RefreshTests.GameServer/Tests/Levels/ReuploadDetectionTests.cs
Closes #715 
adding one of the 4  case insensitive prefixes `(reupload)` `[reupload]` `(archive)` `[archive)` to the level title will automatically mark it as`isReUpload`
additionally adding ?op.{username} to the description anywhere will populate `OriginalPublisher` automatically using a simplistic attributes thingy
=> mark level as reupload by prefix + specify original publisher

Refresh.Database/GameDatabaseContext.Pins.cs, Refresh.Database/Migrations/20250705101737_ProfilePinRelationUpdatingFix.cs, Refresh.Database/Migrations/GameDatabaseContextModelSnapshot.cs, Refresh.Database/Models/Relations/ProfilePinRelation.cs
This fixes profile pin update failures if you either move a profile pin, or if you try setting the same pin as a profile pin in multiple games, by reworking the profile pin updating method and editing the primary key of `ProfilePinRelation`.
I have replaced `PinId` with `Index` in the primary key as a part of fixing the former bug, because I think updating profile pins per index instead of per pin ID helps keep the updating method easier and more reliable, the primary key already has to be updated to fix the latter bug, and the order of profile pins is probably more important than checking if a user has duplicate profile pins set for one game, which even if anyone somehow manages to do that, I don't think it will negatively impact anything anyway.
=> Fix profile pin updating bugs

Refresh.Core/Extensions/GamePlaylistExtensions.cs, Refresh.Database/Extensions/GamePlaylistExtensions.cs, Refresh.Database/GameDatabaseContext.Playlists.cs, Refresh.Database/GameDatabaseContext.Users.cs, Refresh.Database/Migrations/20250705152755_FixPlaylistCreation.cs, Refresh.Database/Migrations/GameDatabaseContextModelSnapshot.cs, Refresh.Database/Models/Playlists/GamePlaylist.cs, Refresh.Database/Models/Users/GameUser.cs, Refresh.Interfaces.Game/Endpoints/DataTypes/Response/GameUserResponse.cs, Refresh.Interfaces.Game/Endpoints/Levels/LevelEndpoints.cs, Refresh.Interfaces.Game/Endpoints/Playlists/Lbp1PlaylistEndpoints.cs, Refresh.Interfaces.Game/Endpoints/Playlists/Lbp3PlaylistEndpoints.cs, Refresh.Interfaces.Game/Types/Playlists/SerializedLbp3Playlist.cs
This fixes everything playlist-related that broke after the Postgres migration, while also cleaning up `GameDatabaseContext.Playlist` in order to achieve that. Also, `GameUser.RootPlaylist` had to be removed, since both it and `GamePlaylist.Publisher` led to EF having a one-to-one relationship between users and playlists, preventing users from creating more than one playlist, and on top of that it was redundant information.
=> Playlist fixes post-database migration

Refresh.Core/Configuration/ConfigStore.cs, Refresh.Core/Configuration/DryArchiveConfig.cs, Refresh.Core/Storage/DryDataStore.cs, Refresh.GameServer/RefreshGameServer.cs, Refresh.WorkerManager/Program.cs, Refresh.Workers/WorkerManager.cs, RefreshTests.GameServer/GameServer/TestRefreshGameServer.cs
- Allows tests to easily generate empty configs. Prevents them from using filesystem configs entirely.
- Configuration loading is behind a lock now. This nullifies the weird random failures caused by unit tests generating config files but doesn't actually serve too much purpose as the codepath isn't hit by unit tests anymore. Kept as it shouldn't technically harm anything.
- Reduces the complexity of config management in `RefreshGameServer` and `TestRefreshGameServer`
- Allows the new `Refresh.WorkerManager` server to easily utilize all the configs from the main GameServer project
=> Simplify and centralize configuration loading mechanisms

Refresh.Database/GameDatabaseContext.Activity.cs, Refresh.Interfaces.Game/Endpoints/ActivityEndpoints.cs, Refresh.Interfaces.Game/Endpoints/DataTypes/Response/GameLevelResponse.cs, Refresh.Interfaces.Game/Types/Activity/Groups/SerializedActivityGroup.cs, Refresh.Interfaces.Game/Types/Activity/SerializedEvents/SerializedEvent.cs
This PR allows story levels to show up in recent activity (and other places as a side-effect, like hearted levels lists), fixes an exception when using the game's `excludeMyself` filter for recent activity, and temporarily disables most of the code for the `/lbp/stream/slot/{type}/{id}` and `/lbp/stream/user2/{username}` endpoints to not have LBP spam them for now until someone finds the reason why the game spams them (I tried for a few hours, but couldn't). Also seperate rate-limiting for the game's activity endpoints incase the game ends up spamming them anyway.
=> In-game recent activity fixes

Refresh.Database/GameDatabaseContext.Leaderboard.cs, RefreshTests.GameServer/Tests/Levels/ScoreLeaderboardTests.cs, RefreshTests.GameServer/Tests/Users/UserActionTests.cs
Fixes a bug where the number 2 players on a level's leaderboard could get spammed with overtake notifications if the number 1 players keep beating their own score. This also slightly optimizes the overtake notification part of `SubmitScore`.
=> Fix score overtake notification spam bug

Refresh.Interfaces.Game/Endpoints/Levels/LeaderboardEndpoints.cs
LBP PSP submits level scores *before* sending /play requests, this caused the server to send a 401 response which prevented the game from connecting
=> Fix submitting level scores from PSP

Refresh.Interfaces.Game/Endpoints/DataTypes/Response/GameLevelResponse.cs, Refresh.Interfaces.Game/Endpoints/Playlists/Lbp3PlaylistEndpoints.cs, Refresh.Interfaces.Game/Types/Levels/GameMinimalLevelResponse.cs, RefreshTests.GameServer/Tests/Levels/PublishEndpointsTests.cs
This makes `GameLevelResponse.FromOld()` depend on `GameMinimalLevelResponse.FromOld()` instead of the other way, to avoid making database calls for information like the user's own review which will not be used for `GameMinimalLevelResponse` anyway, while having as little duplicate code in both methods as possible. Also a few database calls in these methods will only be done if the user is in a game which supports the attributes these calls are for (for example, the user's review won't be gotten if they are in LBP1 or PSP, and the level's skill rewards won't be gotten if the user is not in LBP Vita or a beta build). Also makes LBP3 playlist endpoints return `SerializedMinimalLevelList` instead of `SerializedLevelList`.
=> Optimize some level responses

Refresh.GameServer/Middlewares/DeflateMiddleware.cs
As discussed on Discord. https://discord.com/channels/1049223665243389953/1049225857350254632/1400079015754334259
Pretty much, we haven't been properly compressing some requests for a while, because some requests ask for `gzip` when they are really asking for `deflate`. I'm 99% sure LBP just sends bullshit for the `Accept-Encoding` header half the time.
Lets see how this goes. This may or may not require a revert so I'll try and do some testing first. I'm unsure if this would be LLE/HLE in RPCS3 so it would be good to test on both RPCS3 and PS3. PSP and Vita would also be good to test but I don't have access to those platforms.
Potential solution for #700.
=> Also check for gzip when considering request encodings

Refresh.GameServer/Middlewares/DeflateMiddleware.cs
Reverts LittleBigRefresh/Refresh#908
=> Revert "Also check for gzip when considering request encodings"

Refresh.Database/GameDatabaseContext.Users.cs, Refresh.Database/Query/IApiEditUserRequest.cs, Refresh.Interfaces.APIv3/Endpoints/DataTypes/Request/ApiUpdateUserRequest.cs, Refresh.Interfaces.APIv3/Endpoints/DataTypes/Response/Users/ApiExtendedGameUserResponse.cs, Refresh.Interfaces.APIv3/Endpoints/DataTypes/Response/Users/ApiGameUserResponse.cs, Refresh.Interfaces.APIv3/Endpoints/DataTypes/Response/Users/ApiMinimalUserResponse.cs, Refresh.Interfaces.APIv3/Endpoints/UserApiEndpoints.cs
Also allows users to edit their own Vita and Beta profile pictures through the API, and makes more use of `DataContext.GetIconFromHash` for user responses.
=> Expose VitaIconHash and BetaIconHash to the API

Refresh.Interfaces.Game/Endpoints/Levels/LeaderboardEndpoints.cs
I can't test any of this because I don't have this game, this PR is based on what was reported on Discord (mostly https://discord.com/channels/1049223665243389953/1262898863774105620/1403461202528702546). Also removed an unnessesary Assert.
=> LBP PSP score uploading workarounds

Refresh.Database/GameDatabaseContext.Pins.cs
This is an attempt to fix #938 by making all pin relation retrieval database queries compare the relations' publisher ID instead of the publisher object. Also deduplicates some code related to pin relation updating.
=> Pin database query optimizations

Refresh.Database/GameDatabaseContext.Relations.cs, Refresh.Interfaces.APIv3/Endpoints/DataTypes/Response/Levels/ApiGameLevelResponse.cs, Refresh.Interfaces.Game/Types/Levels/GameMinimalLevelResponse.cs
Optimizes the query used to get the tags for a level. After adding a few tag relations to a few levels on my server and then doing similar testing as in #842, I've got the following results:
With the new query:
```
[09/05/25 11:12:42] [Info] [Request] Served request to 127.0.0.1:36562: 200 OK on GET '/api/v3/levels/newest?count=100' (260ms)
[09/05/25 11:12:42] [Info] [Request] Served request to 127.0.0.1:36584: 200 OK on GET '/api/v3/levels/newest?count=100' (262ms)
[09/05/25 11:12:43] [Info] [Request] Served request to 127.0.0.1:36608: 200 OK on GET '/api/v3/levels/newest?count=100' (250ms)
[09/05/25 11:12:43] [Info] [Request] Served request to 127.0.0.1:36626: 200 OK on GET '/api/v3/levels/newest?count=100' (260ms)
[09/05/25 11:12:44] [Info] [Request] Served request to 127.0.0.1:36650: …
```
=> Optimize query for getting tags for a level
