LittleBigRefresh/Refresh

Refresh.GameServer/Endpoints/LicenseEndpoints.cs
Currently just a stub that returns an empty string, with a TODO for once configs get implemented
=> Implement /announce endpoint

Refresh.GameServer/Endpoints/AuthenticationEndpoints.cs
Reads from a file, and warns if missing
=> Implement /network_settings.nws endpoint

.gitignore, CONTRIBUTING.md, README.md
This is just a starting point, do tell if you want me to make any sort of tone changes, wording, etc.!
If you like it, I'll continue writing it.
=> Starting point for CONTRIBUTORS.md?

Refresh.GameServer/Database/RealmDatabaseContext.cs, Refresh.GameServer/Database/RealmDatabaseProvider.cs, Refresh.GameServer/Startup.cs, Refresh.HttpServer/Database/Dummy/DummyDatabaseProvider.cs, Refresh.HttpServer/Database/IDatabaseProvider.cs, Refresh.HttpServer/RefreshHttpServer.cs, RefreshTests.HttpServer/Database/TestSwitchDatabaseProvider.cs
=> Dont create so many database contexts, and dont create database contexts if not needed

Refresh.GameServer/Database/RealmDatabaseContext.cs, Refresh.GameServer/Endpoints/Api/LevelApiEndpoints.cs, Refresh.GameServer/Endpoints/Api/UserApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiEndpointAttribute.cs, Refresh.GameServer/Endpoints/AutodiscoverEndpoints.cs, Refresh.GameServer/Endpoints/Game/CommentEndpoints.cs, Refresh.GameServer/Endpoints/Game/Handshake/AuthenticationEndpoints.cs, Refresh.GameServer/Endpoints/Game/Handshake/LicenseEndpoints.cs, Refresh.GameServer/Endpoints/Game/Handshake/MetadataEndpoints.cs, Refresh.GameServer/Endpoints/Game/Levels/LevelEndpoints.cs, Refresh.GameServer/Endpoints/Game/Levels/PublishEndpoints.cs, Refresh.GameServer/Endpoints/Game/PresenceEndpoints.cs, Refresh.GameServer/Endpoints/Game/ResourceEndpoints.cs, Refresh.GameServer/Endpoints/Game/UserEndpoints.cs, Refresh.GameServer/Endpoints/GameEndpointAttribute.cs, Refresh.GameServer/Extensions/RequestContextExtensions.cs, Refresh.GameServer/Refresh.GameServer.csproj, Refresh.GameServer/Types/GameLocation.cs, Refresh.GameServer/Types/Levels/Categories/ByUserLevelCategory.cs, Refresh.GameServer/Types/Levels/Categories/CategoryHandler.cs, Refresh.GameServer/Types/Levels/Categories/LevelCategory.cs, Refresh.GameServer/Types/Levels/Categories/SearchLevelCategory.cs, Refresh.GameServer/Types/Levels/GameLevel.cs, Refresh.GameServer/Types/Lists/ResourceList.cs, Refresh.GameServer/Types/UserData/GameUser.cs, Refresh.GameServer/Types/UserData/UserPins.cs, Refresh.GameServer/Types/Visibility.cs
Laying the groundwork for the website
- Ability to fetch users by name & UUID
```http
GET http://localhost:10061/api/v2/user/uuid/63cb507c845365e0d83cadc4 HTTP/1.1
GET http://localhost:10061/api/v2/user/name/jvyden420 HTTP/1.1
{"UserId":"63cb507c845365e0d83cadc4","Username":"jvyden420","IconHash":"0","Description":"","Location":{"X":11684,"Y":18080}}
```
- Move level categories to dedicated class-based system - write once and it will show up in LBP1/2, the API, and in the future LBP3's category system
- Ability to fetch levels by category
```http
GET http://localhost:10061/api/v2/levels/newest HTTP/1.1
[{"LevelId":1,"Title":"aaaa","IconHash":"g10682","Description":"a","Location":{"X":22968,"Y":8478},"PublishDate":1674446588,"UpdateDate":1674446588,"Publisher"{"UserId":"63cb507c845365e0d83c …
```
=> API & Level Categories

Refresh.GameServer/Database/RealmDatabaseContext.Reports.cs, Refresh.GameServer/Database/RealmDatabaseProvider.cs, Refresh.GameServer/Endpoints/Game/ReportingEndpoints.cs, Refresh.GameServer/Endpoints/Game/ResourceEndpoints.cs, Refresh.GameServer/Types/Report/GriefReport.cs, Refresh.GameServer/Types/Report/GriefReportType.cs, Refresh.GameServer/Types/Report/InfoBubble.cs, Refresh.GameServer/Types/Report/Marqee.cs, Refresh.GameServer/Types/Report/Player.cs, Refresh.GameServer/Types/Report/Rect.cs, Refresh.GameServer/Types/Report/ScreenElements.cs, Refresh.GameServer/Types/Report/ScreenRect.cs, Refresh.GameServer/Types/Report/Slot.cs
=> Grief reports

Refresh.GameServer/Database/GameDatabaseContext.Photos.cs, Refresh.GameServer/Endpoints/ApiV3/ApiTypes/Errors/ApiValidationError.cs, Refresh.GameServer/Endpoints/ApiV3/PhotoApiEndpoints.cs, Refresh.GameServer/Endpoints/Game/PhotoEndpoints.cs
https://github.com/LittleBigRefresh/Refresh/assets/51852312/73eb9aab-9b3e-4df8-ba1e-d73ad2b2b72b
=> Implement Deleting Photos

Refresh.GameServer/Types/Matching/MatchMethods/FindRoomMethod.cs
=> Match: Discriminate between platforms and pick random room

Refresh.GameServer/Endpoints/Game/Levels/LeaderboardEndpoints.cs
Just validates score is non-negative, which is an impossible scenario in normal gameplay
=> Leaderboard: Basic score validation

Refresh.GameServer/Types/Matching/SerializedRoomData.cs
=> Fix duplicate JSON property error 

Refresh.GameServer/RefreshGameServer.cs, Refresh.GameServer/Workers/DiscordIntegrationWorker.cs
=> Set invariant culture on startup

Refresh.GameServer/Services/MatchService.Parsing.cs, RefreshTests.GameServer/Tests/Matching/MatchParsingTests.cs
=> Dont crash when parsing invalid IPs

Refresh.GameServer/Database/GameDatabaseContext.Comments.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/Game/CommentEndpoints.cs, Refresh.GameServer/Types/Levels/GameLevel.cs
=> Implement level comments and comment deletion

Refresh.GameServer/Endpoints/Game/ModerationEndpoints.cs, Refresh.GameServer/Types/UserData/Filtering/SerializedTextList.cs
Not doing this caused some PSP levels to fail to upload, crashing the console
=> Send allOk response for batch filtering

RefreshTests.GameServer/RefreshTests.GameServer.csproj, RefreshTests.GameServer/Tests/Users/UserRetrievalTests.cs
Closes #163
The weird extra stuff was added by rider, so im assuming whatever its doing is good, since the analyzers do seem to run
=> Update NUnit.Analyzers from 3.6.1 to 3.8.0

Refresh.GameServer/Database/GameDatabaseContext.Relations.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs, Refresh.GameServer/Endpoints/Game/Levels/LevelEndpoints.cs, Refresh.GameServer/Types/Legacy/LegacyGameLevel.cs, Refresh.GameServer/Types/Levels/Categories/CategoryService.cs, Refresh.GameServer/Types/Levels/Categories/LevelCategory.cs, Refresh.GameServer/Types/Levels/GameLevel.cs, Refresh.GameServer/Types/Levels/GameMinimalLevelResponse.cs, Refresh.GameServer/Types/Reviews/RatingType.cs
=> LBP1 ratings display + `/slots/highestRated`

Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/ApiV3/ResourceApiEndpoints.cs, Refresh.GameServer/Endpoints/Game/ActivityEndpoints.cs, Refresh.GameServer/Endpoints/Game/Handshake/AuthenticationEndpoints.cs, Refresh.GameServer/Importing/AssetImporter.cs, Refresh.GameServer/Importing/ImageImporter.Conversions.cs, Refresh.GameServer/Importing/ImageImporter.cs, Refresh.GameServer/Importing/TexStream.cs, Refresh.GameServer/Types/Assets/GameAsset.cs
This reduces allocations by a *lot*, and speeds up the TEX conversion process
This PR is a necessary precursor to #187
=> Stream TEX files from disk + TGA -> PNG, Improve PSP asset support

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Endpoints/Game/Levels/LeaderboardEndpoints.cs, RefreshTests.GameServer/HttpContentExtensions.cs, RefreshTests.GameServer/ObjectExtensions.cs, RefreshTests.GameServer/Tests/Authentication/AuthenticationIntegrationTests.cs, RefreshTests.GameServer/Tests/Levels/ScoreLeaderboardTests.cs
This PR adds 100% test coverage for LeaderboardEndpoints
=> Road to 100% endpoint test coverage (Part 1/?)

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs
=> fixup for dumb bad code not clearing score events when levels are deleted

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseContext.Relations.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiLevelCategoryResponse.cs, Refresh.GameServer/Endpoints/ApiV3/LevelApiEndpoints.cs, Refresh.GameServer/Endpoints/Game/ActivityEndpoints.cs, Refresh.GameServer/Endpoints/Game/Levels/FilterSettings/GameFilterType.cs, Refresh.GameServer/Endpoints/Game/Levels/FilterSettings/LevelFilterSettings.cs, Refresh.GameServer/Endpoints/Game/Levels/FilterSettings/MoveFilterType.cs, Refresh.GameServer/Endpoints/Game/Levels/LevelEndpoints.cs, Refresh.GameServer/Extensions/LevelEnumerableExtensions.cs, Refresh.GameServer/Extensions/RequestContextExtensions.cs, Refresh.GameServer/Types/Levels/Categories/ByUserLevelCategory.cs, Refresh.GameServer/Types/Levels/Categories/CategoryService.cs, Refresh.GameServer/Types/Levels/Categories/CurrentlyPlayingCategory.cs, Refresh.GameServer/Types/Levels/Categories/DeveloperLevelsCategory.cs, Refresh.GameServer/Types/Levels/Categories/FavouriteSlotsByUserCategory.cs, Refresh.GameServer/Types/Levels/Categories/HighestRatedLevelsCategory.cs, Refresh.GameServer/Types/Levels/Categories/LevelCategory.cs, Refresh.GameServer/Types/Levels/Categories/MostHeartedLevelsCategory.cs, Refresh.GameServer/Types/Levels/Categories/MostReplayedLevelsCategory.cs, Refresh.GameServer/Types/Levels/Categories/MostUniquelyPlayedLevelsCategory.cs, Refresh.GameServer/Types/Levels/Categories/NewestLevelsCategory.cs, Refresh.GameServer/Types/Levels/Categories/QueuedLevelsByUserCategory.cs, Refresh.GameServer/Types/Levels/Categories/RandomLevelsCategory.cs, Refresh.GameServer/Types/Levels/Categories/SearchLevelCategory.cs, Refresh.GameServer/Types/Levels/Categories/SerializedCategory.cs, Refresh.GameServer/Types/Levels/Categories/TeamPickedLevelsCategory.cs, RefreshTests.GameServer/Tests/Levels/PublishEndpointsTests.cs
I'm not 100% happy with the categories refactor, but it was fixes a lot of the type safety and flexibility concerns i was having. There is probably a better way to do this, but i was unable to figure out anything better than "make everything abstract"
=> Refactor categories + implement game, player, and self filtering

Refresh.GameServer/Types/Levels/Categories/CoolLevelsCategory.cs
this is the THIRD cool levels endpoint...
=> psp cool levels

.github/workflows/dotnet.yml, Refresh.GameServer/Importing/Gtf/GtfDecoder.cs, Refresh.GameServer/Refresh.GameServer.csproj, Refresh.GameServer/Types/Levels/Categories/CategoryService.cs, RefreshTests.GameServer/RefreshTests.GameServer.csproj, global.json
This change can be made independently of Bunkum, since the .NET 7 version still works under 8.
=> Support .NET 8

Refresh.GameServer/Refresh.GameServer.csproj, Refresh.GameServer/Services/SmtpService.cs
=> Switch to MailKit for SMTP

Refresh.GameServer/Database/GameDatabaseContext.Users.cs, Refresh.GameServer/Endpoints/Game/UserEndpoints.cs, Refresh.GameServer/Types/UserData/SerializedUpdateData.cs
Removes a massive footgun and fixes #184
=> GameDatabaseContext: Refactor UpdateUserData

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Endpoints/ApiV3/Admin/AdminLevelApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Request/ApiAdminEditLevelRequest.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Request/ApiEditLevelRequest.cs, Refresh.GameServer/Endpoints/ApiV3/LevelApiEndpoints.cs, RefreshTests.GameServer/TestContext.cs, RefreshTests.GameServer/Tests/ApiV3/EditApiTests.cs
Also adds the ability for admins to adjust the level's GameVersion
Closes #129
=> Allow admins to edit user's levels

Refresh.GameServer/Database/GameDatabaseContext.Users.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/Game/Handshake/AuthenticationEndpoints.cs, Refresh.GameServer/Services/CommandService.cs, Refresh.GameServer/Services/MatchService.cs, Refresh.GameServer/Types/Matching/MatchMethods/FindRoomMethod.cs, Refresh.GameServer/Types/UserData/GameUser.cs
This is in preparation of #282
=> MatchService + GameUser: Move force matches to GameUser

Refresh.GameServer/Extensions/LevelEnumerableExtensions.cs
=> Filter out sub-levels from level results.

Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/Admin/ApiAdminQueuedRegistrationResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiActivityPageResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiErrorResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiEventResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiExtendedGameUserResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiGameAnnouncementResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiGameAssetResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiGameIpVerificationRequestResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiGameLevelResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiGameNotificationResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiGamePhotoResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiGamePhotoSubjectResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiGameRoomPlayerResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiGameRoomResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiGameScoreResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiGameSkillRewardResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiGameUserResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiLevelCategoryResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiParameterResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiRequestStatisticsResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiRouteResponse.cs, Refresh.GameServer/Endpoints/ApiV3/LevelApiEndpoints.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameUserResponse.cs, Refresh.GameServer/Types/Assets/GameAsset.Conversion.cs, Refresh.GameServer/Types/Legacy/LegacyGameLevel.cs, Refresh.GameServer/Types/Legacy/LegacyGameUser.cs, Refresh.GameServer/Types/Levels/GameMinimalLevelResponse.cs
`.Select` is an _interesting_ footgun i did not consider until now
=> Show converted icons in category level previews and activity

Refresh.GameServer/Database/GameDatabaseContext.Activity.cs, Refresh.GameServer/Endpoints/ApiV3/ActivityApiEndpoints.cs, Refresh.GameServer/Endpoints/Game/ActivityEndpoints.cs, Refresh.GameServer/Types/Activity/ActivityPage.cs, Refresh.GameServer/Types/Activity/ActivityQueryParameters.cs, Refresh.GameServer/Workers/DiscordIntegrationWorker.cs
Only the first half is done so far, we still show the whole server recent activity log to all users. The only current new changes is the implementation of the filters.
=> Implement recent activity filters, and show less types to users in-game

Refresh.GameServer/Endpoints/Game/Handshake/WelcomeEndpoints.cs
=> Add server contact info to EULA

Refresh.GameServer/CommandLineManager.cs, Refresh.GameServer/RefreshGameServer.cs
Tries to bring things more in line with how other CLIs are used, and cleans up the code a bit.
Closes #387
=> CLI refactor

Refresh.GameServer/Endpoints/ApiV3/ApiTypes/Errors/ApiAuthenticationError.cs
red alert!!!!!!!
this is a critical issue and should be merged asap!!!!!!!! minor typos are unacceptable!!!!!!!11!111111 :OOOO
=> fix ApiAuthenticationError typos

Refresh.GameServer/Workers/CoolLevelsWorker.cs
I've noticed that users sometimes see a new level and downvote it, immediately causing the level's CR to go negative. I fixed this by giving a bonus score of 20 points to allow new levels more chance to survive in Cool Levels.
Decay is still a thing of course, so these points won't last forever.
I also noticed a restricted user who still has levels uploaded being at the top of Cool Levels, so I'm hoping to put a stop to that with a penalty. We should reconsider showing these levels in *all* level lists. Maybe not for restricted users, but especially for banned users - but that's not within scope for this PR.
=> Fix a couple flaws with Cool Levels

Refresh.GameServer/Endpoints/ApiV3/AuthenticationApiEndpoints.cs, Refresh.GameServer/Endpoints/Game/Handshake/AuthenticationEndpoints.cs, Refresh.GameServer/Endpoints/Game/ResourceEndpoints.cs, Refresh.GameServer/Types/UserData/GameUser.cs
- Shows role instead of user id in logs, e.g. `jvyden420 (Admin)`
- Logs authentication successes, e.g. when a user logs in, logs out, or refreshes a token
- Logs assets that were uploaded and who uploaded them
=> Several improvements to logging

Refresh.GameServer/Importing/Importer.cs, Refresh.GameServer/Types/Assets/AssetSafetyLevel.cs, Refresh.GameServer/Types/Assets/GameAsset.Conversion.cs, Refresh.GameServer/Types/Assets/GameAssetType.cs
=> Support LBP3 level chunks

Refresh.GameServer/Authentication/TokenPlatform.cs, Refresh.GameServer/Endpoints/Game/Handshake/AuthenticationEndpoints.cs
Untested, but I think this should be okay.
=> PS4 OAuth support

Refresh.GameServer/Database/GameDatabaseContext.Contests.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/ApiV3/Admin/AdminContestApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiV3/ApiTypes/Errors/ApiNotFoundError.cs, Refresh.GameServer/Endpoints/ApiV3/ApiTypes/Errors/ApiValidationError.cs, Refresh.GameServer/Endpoints/ApiV3/ContestApiEndpoints.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Request/ApiContestRequest.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiContestResponse.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiInstanceResponse.cs, Refresh.GameServer/Endpoints/ApiV3/InstanceApiEndpoints.cs, Refresh.GameServer/Types/Contests/GameContest.cs, Refresh.GameServer/Types/Levels/Categories/CategoryService.cs, Refresh.GameServer/Types/Levels/Categories/ContestCategory.cs, Refresh.GameServer/Types/Levels/GameLevel.cs, RefreshTests.GameServer/TestContext.cs, RefreshTests.GameServer/Tests/Levels/ContestTests.cs
Implements and closes #416
Someone is planning to run a contest with us soon, let's get this supported for them :)
=> API Support for Contests

Refresh.GameServer/Authentication/TokenPlatform.cs, Refresh.GameServer/Endpoints/Game/Handshake/AuthenticationEndpoints.cs
Reverts LittleBigRefresh/Refresh#411
=> Revert "PS4 OAuth support"

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs
=> Fix re-uploaded levels with no OriginalPublisher

Refresh.GameServer/Configuration/GameServerConfig.cs, Refresh.GameServer/Endpoints/Game/Handshake/AuthenticationEndpoints.cs, Refresh.GameServer/Endpoints/Game/Handshake/MetadataEndpoints.cs, Refresh.GameServer/Services/MatchService.cs, Refresh.GameServer/Types/Challenges/SerializedGameChallengeList.cs, Refresh.GameServer/Types/Matching/MatchMethods/FindRoomMethod.cs
Closes #440 
Closes #439
Closes #428
Closes #427 
Closes #398 
#426 stays open until we allow users to specify challenges (ideally through the database and a site UI)
=> LBP3 batch fixes

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Workers/CoolLevelsWorker.cs, Refresh.GameServer/Workers/DiscordIntegrationWorker.cs, Refresh.GameServer/Workers/ExpiredObjectWorker.cs, Refresh.GameServer/Workers/IWorker.cs, Refresh.GameServer/Workers/PunishmentExpiryWorker.cs, Refresh.GameServer/Workers/WorkerManager.cs, RefreshTests.GameServer/Tests/Workers/PunishmentExpiryTests.cs
I recommend reviewing commit-by-commit.
=> Cool levels & workers optimizations

Refresh.GameServer/Refresh.GameServer.csproj
ASP.NET does this, it's probably best that we do too.
https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/workstation-server-gc
=> Enable ServerGarbageCollection

Refresh.GameServer/Endpoints/ApiV3/DocumentationApiEndpoints.cs
=> Add extra sass to the documentation API documentation

Refresh.GameServer/Endpoints/Game/Levels/FilterSettings/LevelFilterSettings.cs
minor copy paste error detected, pull request GO!!!
=> fix mistake in filtersettings summaries

Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs, Refresh.GameServer/Endpoints/Game/Levels/LevelEndpoints.cs, Refresh.GameServer/Types/Levels/GameMinimalLevelResponse.cs
god this game is a disaster
See this thread for why we need to revert this on LBP2 
https://canary.discord.com/channels/1049223665243389953/1240476031786156162/1240477912516399237
=> Fix playhash on LBP2

Refresh.GameServer/Endpoints/Game/AnnouncementEndpoints.cs
Includes a bonus refactor to how /announce works for ABSOLUTELY FREE!
=> Ability to display contests in-game on the announcements screen

Refresh.GameServer/Endpoints/Game/MatchingEndpoints.cs, Refresh.GameServer/Services/MatchService.Parsing.cs, Refresh.GameServer/Services/MatchService.cs, Refresh.GameServer/Types/Matching/GameRoom.cs, Refresh.GameServer/Types/Matching/IRoomAccessor.cs, Refresh.GameServer/Types/Matching/MatchMethods/CreateRoomMethod.cs, Refresh.GameServer/Types/Matching/MatchMethods/FindRoomMethod.cs, Refresh.GameServer/Types/Matching/MatchMethods/UpdatePlayersInRoomMethod.cs, Refresh.GameServer/Types/Matching/MatchMethods/UpdateRoomDataMethod.cs, Refresh.GameServer/Types/Matching/RoomAccessors/InMemoryRoomAccessor.cs, Refresh.GameServer/Types/Matching/SerializedRoomData.cs
=> Matching: Vita + PassedNoJoinPoint + Better slots handling

Refresh.GameServer/Database/GameDatabaseContext.Users.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Request/ApiUpdateUserRequest.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/Users/ApiExtendedGameUserResponse.cs, Refresh.GameServer/Endpoints/Game/Handshake/MetadataEndpoints.cs, Refresh.GameServer/Types/UserData/GameUser.cs, Refresh.GameServer/Types/UserData/SerializedPrivacySettings.cs
This does not implement the functionality, but it means we are now storing all the relevant information to make that happen.
=> Metadata: Implement storage/retrieval of level/profile visibility

Refresh.GameServer/CommandLineManager.cs, Refresh.GameServer/Database/GameDatabaseContext.Users.cs, Refresh.GameServer/RefreshGameServer.cs
Closes #518.
Also contains some minor tweaks to how the CLI works in general. Commit-by-commit review is probably best but it's only 54 lines of changes.
=> Ability to fully delete (and soft-delete) users from the CLI

Refresh.GameServer/Database/GameDatabaseContext.Assets.cs, Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseContext.Notifications.cs, Refresh.GameServer/Database/GameDatabaseContext.Registration.cs, Refresh.GameServer/Database/GameDatabaseContext.Relations.cs, Refresh.GameServer/Database/GameDatabaseContext.Tokens.cs, Refresh.GameServer/Database/GameDatabaseContext.Users.cs, Refresh.GameServer/Database/RealmDbSet.cs
Makes things wonderfully clean.
=> Allow passing expressions into `RealmDbSet.RemoveRange`

Refresh.GameServer/Authentication/TokenGameUtility.cs
`NPUA81174` was missing from our betas title ID list
=> Add LBP3 US private beta title ID

Refresh.GameServer/Database/GameDatabaseContext.Relations.cs, Refresh.GameServer/Database/GameDatabaseContext.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/Game/ReviewEndpoints.cs, Refresh.GameServer/Types/DatabaseRating.cs, Refresh.GameServer/Types/Relations/RateReviewRelation.cs, Refresh.GameServer/Types/Reviews/ReviewRating.cs, Refresh.GameServer/Types/Reviews/SerializedGameReview.cs
=> Implement rating reviews

Refresh.GameServer/Database/Activity/GameDatabaseContext.Activity.cs, Refresh.GameServer/Database/Activity/GameDatabaseContext.ActivityRead.cs, Refresh.GameServer/Database/Activity/GameDatabaseContext.ActivityWrite.cs, Refresh.GameServer/Database/GameDatabaseContext.Photos.cs, Refresh.GameServer/Endpoints/Game/PhotoEndpoints.cs, Refresh.GameServer/Types/Activity/ActivityPage.cs, Refresh.GameServer/Types/Activity/EventDataType.cs, Refresh.GameServer/Types/Activity/SerializedEvents/SerializedEvent.cs, Refresh.GameServer/Types/Activity/SerializedEvents/SerializedPhotoUploadEvent.cs, Refresh.GameServer/Workers/DiscordIntegrationWorker.cs
=> Implement PhotoUpload recent activity type

Refresh.GameServer/Endpoints/Game/MatchingEndpoints.cs
LBP2 for some reason like to send "null" `Location` items, which look like `"0.0.0.0"`.
While this isn't directly a problem, a bug in the serialization code causes the character *after* the null location to be corrupted, eg. `"0.0.0.0","1.1.1.1"` gets corrupted into `"0.0.0.0""1.1.1.1"`, and `"0.0.0.0"],"` gets corrupted into `"0.0.0.0","`. Both of these cases are invalid JSON syntax and a problem.
To fix this issue, I iterate over the match body sent, and find the any instances of `"0.0.0.0"`, I then check what character is *after* the null string, if it is a `"`, then I know that it has corrupted a `,`, since the only times a quote will be after that, is if another string is meant to be in the array. If the next character is `,`, then I know that it has corrupted a `]`, since the only …
=> MatchingEndpoints: Fixup corrupted strings sent by the game.

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs
=> Order by publish date for adventures category

Refresh.GameServer/Endpoints/Game/Levels/PublishEndpoints.cs
PSP levels are not categorized as "Level" assets.
=> Dont check level asset type on PSP

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs
=> Remove reviews when deleting levels

Refresh.GameServer/Endpoints/Game/Levels/PublishEndpoints.cs
=> Allow duplicate level uploads if the user is the original author

Refresh.Common/Constants/FakeUserConstants.cs, Refresh.Common/Constants/SystemUsers.cs, Refresh.Common/Constants/UgcLimits.cs, Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseContext.Users.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameUserResponse.cs, Refresh.GameServer/Endpoints/Game/Levels/PublishEndpoints.cs, Refresh.GameServer/Endpoints/Game/UserEndpoints.cs, RefreshTests.GameServer/Tests/Levels/PublishEndpointsTests.cs
Applied better naming, brought in some variables, applied them to some areas where they weren't used, etc.
Makes a lot more sense in my head this way.
=> Refactor constants in `Refresh.Common`

Refresh.GameServer/Database/GameDatabaseContext.Users.cs, Refresh.GameServer/Database/GameDatabaseProvider.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/Users/ApiGameUserResponse.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameUserResponse.cs, Refresh.GameServer/Types/Data/DataContext.cs, Refresh.GameServer/Types/UserData/GameUser.cs, Refresh.GameServer/Types/UserData/SerializedUpdateData.cs
=> Store user's yay/boo/meh faces

Refresh.GameServer/Database/GameDatabaseContext.Relations.cs, Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameLevelResponse.cs
Closes #616, and hopefully closes #456.
=> Report more details in `GameLevelResponse`

Refresh.GameServer/Configuration/IntegrationConfig.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiInstanceResponse.cs, Refresh.GameServer/Endpoints/ApiV3/InstanceApiEndpoints.cs
This PR resolves #237. Very basic API implementation, doesn't default to anything currently. Let me know if it should.
=> Add API field and integration config entry for WebsiteLogoUrl

Refresh.GameServer/Database/GameDatabaseContext.Relations.cs
This makes the reviews posted under a level get sorted by ratio (most liked to most disliked) and the reviews posted by a user get sorted from newest to oldest.
=> Review sorting improvements

.github/workflows/dotnet.yml, .github/workflows/release.yml, CONTRIBUTING.md, Dockerfile, HttpsProxy.Dockerfile, PresenceServer.Dockerfile, Refresh.Common/Refresh.Common.csproj, Refresh.GameServer/FodyWeavers.xsd, Refresh.GameServer/Refresh.GameServer.csproj, Refresh.HttpsProxy/Refresh.HttpsProxy.csproj, Refresh.PresenceServer/Refresh.PresenceServer.csproj, Refresh.PresenceServer/Server/PresenceServer.cs, RefreshTests.GameServer/RefreshTests.GameServer.csproj, global.json
This upgrades all projects and workflows in the solution to .NET 9. I've also updated some code that has requested to use new .NET 9 features.
Should be fully compatible.
=> Upgrade to .NET 9

Refresh.GameServer/Database/GameDatabaseContext.Levels.cs, Refresh.GameServer/Database/GameDatabaseContext.Users.cs, Refresh.GameServer/Endpoints/Game/UserEndpoints.cs, Refresh.GameServer/Types/Levels/SerializedLevelLocation.cs, Refresh.GameServer/Types/UserData/SerializedUpdateData.cs
=> Ability to move levels while decorating planets

Refresh.GameServer/Configuration/IntegrationConfig.cs, Refresh.GameServer/Endpoints/ApiV3/DataTypes/Response/ApiInstanceResponse.cs, Refresh.GameServer/Endpoints/ApiV3/InstanceApiEndpoints.cs
=> Config option for default theme

.idea/.idea.Refresh/.idea/.name, Refresh.GameServer/Endpoints/Game/Levels/PublishEndpoints.cs
Values reviewed by @Toastbrot236
=> Add rate-limit for level publishing

Refresh.Common/Extensions/RequestContextExtensions.cs, Refresh.GameServer/Configuration/GameServerConfig.cs, Refresh.GameServer/Endpoints/Game/Handshake/AuthenticationEndpoints.cs, Refresh.sln.DotSettings, RefreshTests.GameServer/Tests/Authentication/PatchworkValidationTests.cs
Opening as draft as versioning scheme isn't finalized yet.
=> Add validation for patchwork useragents

RefreshTests.GameServer/Tests/ApiV3/UserApiTests.cs
This fixes some warnings which VS Code has now started to treat as errors.
=> Fix some warnings

Dockerfile, HttpsProxy.Dockerfile, PresenceServer.Dockerfile
https://docs.docker.com/reference/build-checks/legacy-key-value-format/
=> Move away from deprecated ENV syntax in Dockerfiles

Refresh.Database/Compatibility/RealmPostgresPolyfills.cs, Refresh.Database/Extensions/DbSetExtensions.cs, Refresh.Database/GameDatabaseContext.Levels.cs, Refresh.Database/GameDatabaseContext.Relations.cs, Refresh.Database/GameDatabaseContext.cs, Refresh.Database/GameDatabaseProvider.cs, Refresh.Database/Migrations/20250614045619_RemoveRealmWeirdness.cs, Refresh.Database/Migrations/GameDatabaseContextModelSnapshot.cs, Refresh.Database/Models/Assets/GameAsset.cs, Refresh.Database/Models/Levels/GameLevel.cs, Refresh.Database/Models/Levels/GameSkillReward.cs, Refresh.Interfaces.APIv3/Endpoints/DataTypes/Response/Levels/ApiGameLevelResponse.cs, Refresh.Interfaces.Game/Endpoints/DataTypes/Request/GameLevelRequest.cs, Refresh.Interfaces.Game/Endpoints/DataTypes/Response/GameLevelResponse.cs, Refresh.Interfaces.Game/Endpoints/Levels/PublishEndpoints.cs, RefreshTests.GameServer/Tests/Levels/PublishEndpointsTests.cs
This removes a lot of the oddities and quirks that worked with Realm but will not work with Postgres.
This is likely the final state the Realm database will be in.
=> Remove realm weirdness

Refresh.Database/GameDatabaseContext.Tokens.cs, Refresh.Database/Migrations/20250625165615_CleanupDuplicateFirstSignInEvents.cs, Refresh.Database/Migrations/GameDatabaseContextModelSnapshot.cs
=> Fix and clean up duplicate signins

Refresh.Database/Migrations/20250705101737_ProfilePinRelationUpdatingFix.cs, Refresh.Database/Migrations/20250705152755_FixPlaylistCreation.cs
I just now found out the attributes below need to be added to migrations in order for EF to apply them to a database in most cases.
=> Fix some migrations not getting applied

Refresh.Core/Authentication/TokenGameUtility.cs
Reported by RukeRPCS3 via support email.
=> Add BCAS20113 as LBP2 Asia Disc

Refresh.Database/GameDatabaseContext.Levels.cs
=> Fix deleting levels which have scores

README.md
=> readme heart looks better

Refresh.Core/Authentication/TokenGameUtility.cs
Unsure if this is actually meant to be LBP2 Asia Digital, but I'm at a loss when it comes to the title-id situation.
=> Add LBP2 Hong Kong Digital Title-ID

Refresh.Database/GameDatabaseContext.Workers.cs, Refresh.Database/Migrations/20250726043747_AddClassToJobState.cs, Refresh.Database/Migrations/GameDatabaseContextModelSnapshot.cs, Refresh.Database/Models/Workers/PersistentJobState.cs, Refresh.Workers/MigrationJob.cs, Refresh.Workers/State/IJobStoresState.cs, Refresh.Workers/WorkerManager.cs
=> Add WorkerClass to PersistentJobState

Refresh.Interfaces.Game/Endpoints/PhotoEndpoints.cs
This website allows direct uploading of custom stickers. Since the website announces itself we can just go ahead and block it for now, since I'm seeing suspicious behavior relating to this. Config toggles for this can be made for other instances on request.
I'm tired, boss.
=> Explicitly block photos from LBPMod.me
